### PR TITLE
makes broc and xander juice actually obtainable

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

fixes broc juice unobtainability

## Why It's Good For The Game

THE JUICE MUST FLOW
THE JUICE MUST FLOW

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: broc/xander tea obtained by heating broc/xander juice and water
fix: brocjuice now obtained by juicng broc (xander too)
/:cl:

### CODE REVIEW

**Comment by Snoozer000** [comment]
Im confused. Right now there are three possible outcomes for each wasteland plant. For example:

Xander Juiced=Xander tea
Xander grinded= a mixture of Nutriment/antitoxin/saline glucose solution based off of plant variables like potency.
Xander fermented=Salgam

Broc Juiced=Broc tea
Broc grinded=a mixture of dexalin/saline glucose solution/nutriment bicardine Based off plant variables like potency.
Broc fermented=Broc Brew

If you want to add another layer to this system making some sort of heat activated reagent thats cool. You could argue its needed. You could add a fourth layer to each of these plants and give them some sort of chemical property different than the other three process method. This could be used to plug in holes for tribal shamans like certain surgical supplies being hard to get. But how does this update effect the previous system? does it remove the juice mechanism? There really isnt a reliable heat pad method for other roles like tribals. Unless you make this compatible somehow with bonfire/bonfiregrill. Tribal can use bone mortors or scrap attain an all in one grinder. Other roles have even more advanced grinders.

**Comment by lolman360** [comment]
igniters, zippos, welding tools, bonfires etc can all be used for heating chemicals in a beaker

this doesn't reduce tea availability for tribals, since they can simply juice with bone mortar and then heat using whatever method they have

the new system is:

Xander Juiced=Xander juice
grind/ferment unchanged

Broc Juiced=Broc juice
grind/ferment unchanged

Juice + water + heat = tea

there wasn't really an easy way to get juice into the existing system, as the 'juicing' method (intended for juices not plant reagents) was taken up by tea. this replaces the tea from juicing with juice, which can be further processed into tea

**Comment by Snoozer000** [comment]
Okay, but what is the point of the fix to make the availability of broc/xander juice? If the update is to make it more difficult to make wasteland reagents by adding another layer then I can see the point. in terms of emersion it also makes sense. I would also suggest adding more value to the juiced variants so noobs dont use them on accident as meds but they have no reagents in them. if we can simply juice a plant to get the next reagent being tea which has medical benefits. why are we adding another step to the process for a reagent that has less value then the plant and the tea. I would also argue the juiced/tea variants of wasteland plants is completely underutilized as is. Maybe by tribals and thats it.

Right now broc juice and xander juice have no function what so ever. its only worth one nutriment. Same with xander juice. They appear to be place holders. simply eating the fruit has more value. Why would a plant lose its medicinal properties just from being juiced? A player would with grinding can completely avoid the step of having water on their persons and the need to heat. which appears to be a 2/1 ratio of water juice.

Perhaps buffing the juice reagent to be comparable to the other reagents? broc/xander are right next to each other both in the fruit and juice sections. You can see the value of them together.  If its to be plant(which has grind properties),juice(which has no properties right now/Heated tea(which we already have but there will be another step in the process, and fermentation(barrels) If this were to go through the juices needed to be buffed.

https://github.com/LoneStarF13/LoneStar/blob/d2a7756db55916417521a97cab780a5dbe9e3934/code/modules/reagents/chemistry/reagents/food_reagents.dm#L383

https://github.com/LoneStarF13/LoneStar/blob/d2a7756db55916417521a97cab780a5dbe9e3934/code/modules/fallout/obj/food_and_drinks/wastefood.dm#L147

 But no one has these reagents on hand as it is. At best they will make bitters with the fermented variants. You never see people using juiced tea wasteland reagents as it is? So why add another layer of processing for reagents that are already underutilized? A underutilized reagent that they can simply juice to get already? I suppose if this was a craft recipe to make it more visible maybe it would be used more?

**Comment by lolman360** [comment]
broc and xander juice are used for imitation stimpak juice, they're not useless

**Comment by Snoozer000** [comment]
> broc and xander juice are used for imitation stimpak juice, they're not useless

Broc **flower** and xander **root** are **A M A Z I N G** and are used in imitation stimpak right now in the craft menu.Broc juice and xander juice are not used for anything right now. They have no properties attached to them. As your Pull request states its not even possible to get to them. As far as I can tell this is true.

Here is the code it requires plant. "/obj/item/reagent_containers/food/snacks/grown/broc" not 
https://github.com/LoneStarF13/LoneStar/blob/17c5484f2c7fb6d02c8e08632c25da387e870556/code/datums/components/crafting/recipes/recipes_medicine.dm#L104

imitation stims dont use "/datum/reagent/consumable/brocjuice"
https://github.com/LoneStarF13/LoneStar/blob/d2a7756db55916417521a97cab780a5dbe9e3934/code/modules/reagents/chemistry/reagents/food_reagents.dm#L383

Once again we have 4 out comes right now. The plant as is(acts like grind reagents), the grind which is the chemicals isolated, Tea which is the product of juicing and alcohols which is the product of fermentation.

so once again why should we replace fruit+juicing= tea(a+b=c one step) 
with fruit+juicing=juice+water=tea solution +heat=tea?(a+b=c+d=e+f=g three steps)

Once again it actually does sound like a good idea for emersion reasons. I just want to understand why the juice is worth the squeeze (pun intended). Lets be honest most people probably carry a lighter or a welder with them. making a solution with water is really no different then people making a fermentation solution to mix bitters. arguably easier since you dont need to worry about energy from soda machines or getting bottles from machines for sunset sarsaparilla. This will only screw tribals who use mortar on there persons. 

is it to make it easier to prepare it manually in chem machines? is it easier for a chemwhiz to wait on a chemical heater than grinding? why more difficult for everyone just for chem whiz roles assuming thats the case? You would also need to add properties to juice. Because once again it has no properties. Anyone with no training can get 4broc 4 xander and a syringe will have imitation stimpak. anyone with no training can go get a mortor or an all in one grinder and juice and make tea right now. someone tries to use juice and only gets nutriment because they think its a higher value than plant.

your plan has merit I am just saying theres things missing.
-why more difficult
-why use a reagent that has no properties in the code
-are you going to add properties to broc/xander juice?
-why only those two wasteland plants? almost every wasteland plant has these properties in their own way.

**Comment by lolman360** [comment]
> why more difficult
i don't consider the difficulty increase of any significance
> why use a reagent that has no properties in the code
>are you going to add properties to broc/xander juice
i'm not opposed to making brocjuice and xanderjuice do some healing/other effects etc
> why only those two wasteland plants? almost every wasteland plant has these properties in their own way.
actually this is a good idea, closing this since further changes will be in #299

**Pull request closed without merging**
