### PR TITLE
Haven is better than oasis

### PR DESCRIPTION
**Pull request by Neveralone1744**
## About The Pull Request

A remap and rebranding on oasis into haven. making use of the 2nd stories and adding a casino inside the town for the den to operate out of inside of town.  
haven2
haven1
haven4
haven3 
haven6

## Why It's Good For The Game

oasis has had a rough time since i have been on the server. not only has it been a generally plain place that made it less likely to play, it really served no purpose beyond the followers and the store. with the addition of the den faction to as part of the town as a crime element inside it this will create a conflict that will interest people into playing the law which will then protect the town in general as well as generate more rp. 

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

 add: changes to outside, underground, and above maps for the new town haven

### CODE REVIEW

**Comment by Snoozer000** [comment]
Link says page not found.

**Comment by Neveralone1744** [comment]
> Link says page not found.

should be good now

**Comment by biotear** [comment]
Looks good. I like it. :D

**Comment by Looreydev** [comment]
> cl
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/cl

Should probably fix up the changelog.

**Review by Looreydev — CHANGES_REQUESTED** [review]
image
Change back the file names to:
`Pahrump-Above-3.dmm`
`Pahrump-Surface-2.dmm`
`Pahrump-Underground-1.dmm`

**Comment by Neveralone1744** [comment]
> > cl
> > add: Added new things
> > add: Added more things
> > del: Removed old things
> > tweak: tweaked a few things
> > balance: rebalanced something
> > fix: fixed a few things
> > soundadd: added a new sound thingy
> > sounddel: removed an old sound thingy
> > imageadd: added some icons and images
> > imagedel: deleted some icons and images
> > spellcheck: fixed a few typos
> > code: changed some code
> > refactor: refactored some code
> > config: changed some config setting
> > admin: messed with admin stuff
> > server: something server ops should know
> > /cl
> 
> Should probably fix up the changelog.



> image Change back the file names to: `Pahrump-Above-3.dmm` `Pahrump-Surface-2.dmm` `Pahrump-Underground-1.dmm`

will do sorry was for my own refrence

**Comment by AdamElTablawy** [comment]
why does everything always have to look like shit

can it look less awful poop brown please

**Comment by Neveralone1744** [comment]
> why does everything always have to look like shit
> 
> can it look less awful poop brown please

thats why i threw grass everywhere. the only outside tiles we got is dirt, and sand. their is a grass one but it doesnt look right to the map at all. trust me i tried

**Comment by AllCorruptingWyrm** [comment]
image

Something like this might be refreshing, replace the wood with iron tiles? idk.

**Comment by Neveralone1744** [comment]
> image
> 
> Something like this might be refreshing, replace the wood with iron tiles? idk.

i would go with that grass but it is very vibrant which is very dif. from the rest of the map. though if people like the idea its an easy change.

**Comment by Neveralone1744** [comment]
> image
> 
> Something like this might be refreshing, replace the wood with iron tiles? idk.

i got a guy working on getting me a grass tile more fitting for a wasteland setting. it will not be done before everything is said and done on this pr but when it and the scrap wall one is i will update haven

**Comment by AsterixCodix** [comment]
There are a small variety of grass tile sprites in the files, they're just not tied to any actual tiles

**Comment by Neveralone1744** [comment]
> There are a small variety of grass tile sprites in the files, they're just not tied to any actual tiles

huh alright. well i got a guy working on one too so whichever happens ill throw in. probably not this pr but it will be done

**Comment by SeeminglyTypicalUsername** [comment]
>mfw this still hasn't been test merged

**Comment by VEN0M5** [comment]
> mfw this still hasn't been test merged

Would be funny if it got test merged before the bulk changes 16 hours ago.... I went though the map with the mapper a bunch of stuff like half of the shop having no roofs, people can steal from FoA fridge from the library and the mayor spawn has no roof. These are fixes(hopefully) in the abovementioned bulk changes

**Comment by Neveralone1744** [comment]
heresy! yeah there were alot of small stuff that venom saw that im glad got fixed. im going to leave the map as is from now on on it till it either it is decided it will be merged or not and then update it as necessary in the future

**Comment by AllCorruptingWyrm** [comment]
I do not want to be pushy by any means but I would really like to see this PR'd quickly, Oasis really needs some regeneration and this is going to be it. It allows Mayors to decide on Oasis's gimmick for the round, its still wide open, it has a unique aesthetic and the casino fits perfectly for the future.

**Comment by ScheveningenZonn** [comment]
map conflicts, address pls

**Comment by AllCorruptingWyrm** [comment]
I was talking with Neveralone and they were saying that they'd need the loot PR merged so Alone doesn't erase the work of that PR. It might be worth it given how long the PR has been up.

**Comment by companoo** [comment]
mayor spawns on the eastern highway for some reason and the entrance to the second floor of the mayors manor has a wall in the door

**Comment by Neveralone1744** [comment]
> mayor spawns on the eastern highway for some reason and the entrance to the second floor of the mayors manor has a wall in the door

Thxs I'll figure put why the mayor is working with aliens

**Comment by comrade-dagmar** [comment]
Maybe an addition of houses, I think right above the town hall, with either stairs inside the town hall itself, or stairs outside leading above to it and expanding the roof area a bit out to maximise space and cram a couple of units in the area, I'll try my hand at mapping and showing a mock up. :)

**Comment by Neveralone1744** [comment]
> Maybe an addition of houses, I think right above the town hall, with either stairs inside the town hall itself, or stairs outside leading above to it and expanding the roof area a bit out to maximise space and cram a couple of units in the area, I'll try my hand at mapping and showing a mock up. :)

I'd be interested in seeing this. Currently tho housing is in the vault in the middle of town. Honestly they don't have a lot of life in this first implementation but that was on purpose for 2 reasons. 1) proof of theory. The map needs to get out so I can work on the bigger projects of it or it won't ever. 2) I'm making the vault expanded in steps and other such parts as a pseudo event hopefully with story and effort done by the players and lore team. Tho sure if you see something there throw it at me.

**Comment by comrade-dagmar** [comment]
> > Maybe an addition of houses, I think right above the town hall, with either stairs inside the town hall itself, or stairs outside leading above to it and expanding the roof area a bit out to maximise space and cram a couple of units in the area, I'll try my hand at mapping and showing a mock up. :)
> 
> I'd be interested in seeing this. Currently tho housing is in the vault in the middle of town. Honestly they don't have a lot of life in this first implementation but that was on purpose for 2 reasons. 1) proof of theory. The map needs to get out so I can work on the bigger projects of it or it won't ever. 2) I'm making the vault expanded in steps and other such parts as a pseudo event hopefully with story and effort done by the players and lore team. Tho sure if you see something there throw it at me.

True it does need to get our first! And I was actually thinking about the vault when I saw it but didn't want to pile another thing on, I was already imagining it's usefulness as a town bunker that could be closed in bad events where everyone scatters to it, it could set up oasis as a better faction taking in wastelanders who seek shelter, and you could look at the desert rose vault for some layout ideas. I'll see if I can figure out the house idea when I'm back at my pc!

**Pull request merged**
