### PR TITLE
Fixes to the tribes

### PR DESCRIPTION
**Pull request by AsterixCodix**
## About The Pull Request

Gives the Dead Horses Big Leagues; White Legs, Iron Fist; every tribe not listed, Tagger.

Dead Horses get Big Leagues because it makes more sense. The other two are changed because... I misunderstood what TRAIT_TRIBAL did... 

Closing this, so I can fix a bunch of the issues with the branch before I fix the bugs themselves.

## Why It's Good For The Game

Actually gives all tribes the ability to use the alchemy station and use Tribal chems without tripping balls like a backpacker that discovered a peyote cactus whilst smoking a DMT laced joint that was soaked in LSD.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: Tribal Traits
/:cl:

### CODE REVIEW

**Comment by OliOliOnsiPree** [comment]
👍 
YESSS

**Comment by VEN0M5** [comment]
If you wanted to allow all tribals to use the alchemy table, you would need to give them the machine spirit OR mars teach trait. Looking at the alchemy table code, it only allows people with either of those 2 traits to use em... If I am reading code correctly

**Comment by AsterixCodix** [comment]
> If you wanted to allow all tribals to use the alchemy table, you would need to give them the machine spirit OR mars teach trait. Looking at the alchemy table code, it only allows people with either of those 2 traits to use em... If I am reading code correctly

Oh for the love of...

Making this a draft before more shit goes sideways

**Comment by OliOliOnsiPree** [comment]
> > If you wanted to allow all tribals to use the alchemy table, you would need to give them the machine spirit OR mars teach trait. Looking at the alchemy table code, it only allows people with either of those 2 traits to use em... If I am reading code correctly
> 
> 
> 
> Oh for the love of...
> 
> 
> 
> Making this a draft before more shit goes sideways

So if you do that and remove just that perk from the alchemy table, then it would most likely be a useless perk from the wayfarer 'machine spirits' perk.

**Pull request closed without merging**
