### PR TITLE
Khaaaan

### PR DESCRIPTION
**Pull request by Pebblesthe2nd**
## About The Pull Request

Khans get a facelift

Adds a bunch of icons for khan stuff instead of the microcopic onmobs previously copied. 
Gone over every onmob sprite and fixed tons of pixelation, offsets, etc etc, to make them look better and less fuzzy. Armored jacket gets new art based on the old jacket, so its not literally the same.
Khan uniform now can be toggled to a denim skirt version.
Fixed hair and khan helmets, leather one covers it, others dont. New satchel doesnt cover the whole model in a blobby mess, also the radio no longer is the two white pixels making me annoyed.
Khans also get a proper tattoo.

khaaaans

Loadouts adjusted to get rid of rarely used clutter, beanbag box, handcuffs. All get spiked knuckles instead of machete because cooler. Location of loadout items adjusted so the preview works properly. 9mm pistol removed.
Armory stuff: Machete and 9mm removed from standard, instead some varied stuff added. Knucklegun, piperifle, punch dagger, spiked bat, tire iron. So people can take what they like from there instead of being forced to carry machete + 9mm wich often gets thrown away anyways. One of the greaseguns replaced with a Rockwell for variety, also endless greaseguns already in gang tool, boring to use same.
Drug shelf added to the armory to allow tidier drug lab.
New items: Fur trimmed helmet, bandana, pelt boot, old satchel
Bandolier unfudged: now can take three items, shot gun boxes, lasmusket boxes, grenades, flasks. It makes the belt actually useful. 
Molotov variant thats actually prefilled made for mapping/loadouts.
Knucklegun & lever shotgun updated visually, especially onmobs that were offcentre etc.
Knucklegun remade to take .45 to make it less useless and also .38 is pretty much not used any more.
Gangtool content adjusted for the new stuff

## Why It's Good For The Game

Khans better.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
add: Various khan clothing/armor/ID added
imageadd: khan art lineup redone
tweak: minor loadout adjustments khans.
/:cl:

### CODE REVIEW

**Comment by Malerus** [comment]
- Machete is a very important part of the Khan loadout, at least to be able to cut down trees for set up and other Khan things. 
- Beanbag box is used for non-lethal chimping or capturing with a number of Khans use
- The handcuffs are used, just not all the time. Khans do bounties and merc work, and having cuffs is very necessary.


Consult with the Khan mains first before merging.

**Comment by OneOneThreeEight** [comment]
We're allowed to do a little creative freedom. In the long-term we will be looking to drift ever so slightly from the canon source material while still using it as our muse.

These sprites look gorgeous.

**Comment by Malerus** [comment]
Creative freedom is fine, however, straying from lore where it isn't necessary too, especially when the defining features of a female Khan is jort does raise eyebrows. More variation for Khan clothing is fine, don't get me wrong, however, skirts on a Khan is bit out of left field when they could've been the first approach to giving a different option for the uniform.

**Comment by Pebblesthe2nd** [comment]
> * Machete is a very important part of the Khan loadout, at least to be able to cut down trees for set up and other Khan things.
> * Beanbag box is used for non-lethal chimping or capturing where a number of Khans use this option.
> * The handcuffs are used, just not all the time. Khans do bounties and merc work, and having cuffs is very necessary.
> * Khans either use denim jeans, or denim jorts, so a skirt makes no sense lorewise.

These are minor points but I'll adress them. The TL:dr is jorts will be a thing, the other three is a no, and below is why.

Jorts: Fair enough I suppose, important bit is its short and denim and offers a distinct choice from the standard pants. Visually the difference is almost imperceptible ingame, but since I'm working on Khans anyways I can make jorts too while at it, why not. Some pretty extreme demands for lore accuracy there though, gotta say.

Machetes: are bulky and occupy the belt slot. Spiked knuckles are as cool and give you the minimum utility (woodcutting etc) while just occupying the glove slot. The added melee weapons to the armory and gangtool lets the player customize with less hassle. Theres a ton of options for cutting wood with the stuff around, two machetes in the armory (also forge for making as many more you like) is plenty.

Beanbag box is dirt cheap to print in the ammo bench, and the boxes people spawn with seem to most often end up discarded or recycled. Adding a single box to the armory and we will see how often it just gathers dust. I understand and approve the RP theme of man-catcher, but most don't utilize it, and it's so easy to gear up for it in the once in a blue moon occasion it's wanted.

For handcuffs, same deal more or less, theres two in the armory now, with cable ties existing too it should very rarely be an issue of any sort. Just another item that typically gets discarded. I considered putting it in the enforcer loadout, but again, not all shotgunners want them, and uzi-lovers might, and neither will use them often.

"This could be useful" syndrome causes inevitable loadout bloat. Every single time someone spawns with stuff they don't need and don't want is adding busy work with discarding them, and it creates littering. Its time to try lighter baggage and more optional customization things. Incidentally it will increase Khan equipment diversity and thats rather fitting.

I'll do a little update in a couple hours then its go time.

**Review by Malerus — COMMENTED** [review]
Sure that's fine, however, machetes and other things removed were not mentioned to have been relocated to the armory.

Also, I noticed you added to the chemist role, yet there's no datum path in the loadout listing, so it won't show up.

The line would be 232 for code/modules/jobs/job_types/wasteland.dm

You would want to write:

loadout_options = list(
		/datum/outfit/loadout/enforcer,

/datum/outfit/loadout/khanskirmisher, 

/datum/outfit/loadout/pusher, 
		)


I wrote that on my phone, so the code might not read it well, but that's pretty much what you want.

**Comment by Pebblesthe2nd** [comment]
Hmmm the chemist edit was just off the cuff so it would not be unarmed, did not consider its not enabled. Role seems a bit redundant for the moment so just leaving it inactive for now. The simple and low bloat faction structure with one role, two loadouts, and customization options via gangtool etc is honestly the best design wise in my view, and I am reluctant to add any weight to it. Not saying all factions work with one role, but Khans honestly don't seem to need more.

It was not unreasonable to ask where are the machetes, I had forgotten to actually map them in in the first push, it should all be in order now though. Stuff like the pipe rifle will probably never be used so I'm on the fence about it, it can be used for crafting though, same with the hunting knife, with duct tape you can make a improv bayonet so this content weapon wise is good enough for now, nothing is completely without a use.

Some small changes:;
Discovered the UZI, rockwell and shotgun bat onmobs were incomplete and way misaligned, sorted that when doing the jorts.
Added recycle to knuckledusters, pipe, tire iron and frying pan, so its easy to dispose of lowgrade stuff thats not wanted.

**Review by OneOneThreeEight — CHANGES_REQUESTED** [review]
un-tm'd I have a few issues to bring up.

1. I do feel like it'd be better to just take the principles of the old Khan sprites and just HQ-ify them. I have to agree with the assessment that one of the pairs of the boots here look more like white girl uggs than a great tribe with warrior-raider boots. 
2. The removal of the jacket options seems to have been for the worst for Khan fashion choices.
3. One of the helmets covers hair entirely, which mostly looks not great overall.

I'd ask mostly just because I'm still interested in this PR to review and push later since it does contain some great QOL. I do request the following:

1. The appearance of the plated boots should return for the Khans. Maybe a mix of the appearance of the male/female diesel boots in addition to being plated on the front and on the toe covering.
2. Helmets look good barring the fact they cover hair.
3. More jacket diversity would be good, in addition to craftable war jackets that can be plated up to tier 6 or so.

**Review by TripleShades — COMMENTED** [review]
Please put these back into survivalkit.dm below line 32
You caused the survival kits to have no icon or weight class

icon_state = "survivalkit"
w_class = WEIGHT_CLASS_SMALL

**Comment by Pebblesthe2nd** [comment]
Allright, did an update, fixed the tribal survival kit inheritance error and added a proper drug storage instead of the relabeled alchemy one. This one got new art and takes all sorts of drugs, should be practical.

Added battlecoat, T6 armor, slapped it in the gangtool for 1000 caps for now, so its ingame at least.
Adjusted the hair hiding stuff, without dynamic hair changes its either clipping or no hair, clipping is the better choice of the two so its less like an army, so back to how it was.
Adjusted bunch of stuff, some fuzzy things adjusted, boots blacker etc, all good. Dunno what an ugg is but I fear to find out, black turned out looking better with the outfits anyways.
What you can adjust from start now: alt click for: jorts instead of jeans, vest instead of jacket (armored too), boots to remove/add the shin guard.  Choose faction satchel for the smaller less obtrusive bag if you wanna show off your colors. Gangtool to get fur trimmed helmet, boots.
Also removed the dead end duplicate khan armor in the files that was causing confusion, and some rack duplicates, and made proper inheritance of the khan armor.

Its good to go, its all modular so all the old icon stuff is still sitting where they used to.

**Pull request merged**
