### PR TITLE
More ports [Ready to TM]

### PR DESCRIPTION
**Pull request by TripleShades**
## About The Pull Request
More ports more ports more ports
Will be ready to testmerge once the title changes to include [Ready to Testmerge]!

Port of the port of "Makes the microwave cleanable by the damp rag"
Because who the fuck cleans a microwave with a bar of soap...?
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14121
Port of the port of "Let Me Tell You A Story" #14123
Backend issue, shouldn't be relevant to play but just in case it is.
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14123
~~Fixes laptop and tweaks stacks
Fixing some issues for laptops and lockers/crates
Another closet change
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14447
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14547
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14576~~ This is only partially in right now, I need more time to do the full batch.
You can now shove yourself up on any intent
Pretty explanatory.
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14130
Port of a ports breaking a mirror now gives you a bad omen
Flavor text stuff (I think it's only flavor?)
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14930
Port of a [PORT] Stripping a disconnected player will tell them when they come back (+Lazynull)
Works up to five minutes.
Time values can be modified, everything should be commented in that regard.
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14933
Some hallucination tweaks
Only ports the single line change to hallucination calc, not the supermatter part (since we don't use that here)
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/14960
Removes minesweeper
Code stability, server stability. Yes really, I'm very sorry. Please see original pr for details.
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15232
Makes moving NOT give you nutrition anymore
Basically, even just running around gave you nutrition. Now you should become hungry more naturally.
https://github.com/Citadel-Station-13/Citadel-Station-13/pull/15316

Not a port: Re-enables the ability for players to view their admin notes. This will not let them see notes set to secret.

## Why It's Good For The Game
code

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Microwave can now be cleaned by a damp rag as well as soap.
add: Breaking mirrors now gives you a bad omen
add: Stripping/equipping things to a conscious braindead person (AKA a human owned by a disconnected player) will now give them a message with your visible name and roughly how long ago you touched their stuff when they login again. Touching someone's pockets or adjusting their gear other than equipping/unequipping is not logged. After 5 minutes, you'll have forgotten both their name and exactly how long ago past those 5 minutes it happened. (Credit to Ryll-Ryll)
add: LAZYNULL
del: Removed minesweeper
tweak: you can now shove yourself up in any intent, not just help.
fix: Alien radio code
fix: hallucination now bottoms out at 0
fix: Walking no longer makes you fat.
code: Added LAZYNULL
code: Re-enables View Notes for players
/:cl:

### CODE REVIEW

**Comment by Looreydev** [comment]
@TripleShades 
You should definitely separate ports into different branches and make a Pull Request for every single one opposed to clustering them up like this.

**Comment by TripleShades** [comment]
> @TripleShades You should definitely separate ports into different branches and make a Pull Request for every single one opposed to clustering them up like this.

Hi! I already know that, but I figured it was more important that the codebase become healthier faster first, considering the amount of time that has gone since, apparently, FO13 was rebased to Citcode with no maintenance to it. Also, since Schev hasn't yelled at me for it, I'm going to keep doing this until the code is more up to date because of the sheer backlog of updates, some of which I don't think I can even port in the end.

When I go back to making regular prs, or when I make port prs that do large changes, I'll be making a focused pr instead of a bulk one due to safety/testing reasons, in addition to proper pr etiquette.

**Comment by OneOneThreeEight** [comment]
> Also, since Schev hasn't yelled at me for it, I'm going to keep doing this until the code is more up to date because of the sheer backlog of updates, some of which I don't think I can even port in the end.

In fairness this may be the last time I tolerate a big bunch of ports. Clustering a lot of commits across the repo's files make it more difficult to test merge various other PRs along with this one, and a larger PR with a conglomerate of changes is more difficult to test on-server for functionality as it is more time-consuming of a process

**Comment by Looreydev** [comment]
> I'm going to keep doing this until the code is more up to date
No

**Comment by TripleShades** [comment]
> 

Alright.
So should I close this then?

**Comment by TripleShades** [comment]
Going to close this to redo in smaller, more reasonable prs, while only grouping together things that are related (such as the x3 one linked in the About)

**Pull request closed without merging**
