### PR TITLE
The Tribes of the West

### PR DESCRIPTION
**Pull request by AsterixCodix**
## About The Pull Request

Currently a draft PR.

So, to start with: the Rustwalkers. A tribe of scavengers that worship a triage of machine gods. (Their heavy and light armour have since been altered with purple elements on each, to help differentiate them from Legion troops at a glance.)
Below them, we have the 80s, a warlike tribe that _may_ use and revere vehicles.
image

Here we have the White Legs and the Dead Horses. No introduction is needed.
image

And finally, the Sorrows tribe, complete with their signature weapon, the yao guai gauntlet.
image

This also adds in the Steel Saw and Auto Axe from Fallout 3, which will both be craftable. The Steel Saw should be fine to add to weapon spawn lists but, I'll leave that to more balance-inclined people to decide.

As a few miscellaneous things, I've redone the Yao Guai mob sprite and added in Picket Fences, but unlike its FO4 counterpart, this one just provides the "Tagger" trait.
image

I've also gone through and found every misspelling and corrected it because _why was it even allowed in with a misspelling._
image

Added in 3 "general" trait books based on the SCAV! magazines in Nuka World, that provide crafting recipes for scavenging/scavenged weapons, such as a Chainsaw, Steel Saw and Auto Axe. More to come soon since this is a Draft PR.

## Why It's Good For The Game

Expands on the tribal role, providing a variety of (mostly) lore accurate loadouts and weapons, allowing people to better connect their characters to the tribes we see in Honest Hearts, alongside one that was mentioned and a fifth tribe that is completely homebrew (credit to Doru and Neveralone on the discord for their lore).

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added Sorrows undersuits
add: Added Dead Horses undersuits
add: Added White Legs undersuits
add: Added Eighties undersuits
add: Added Rustwalkers undersuits
add: Added Sorrows armour
add: Added Dead Horses armours
add: Added White Legs armours
add: Added Eighties armours
add: Added Rustwalkers armours
add: Added Steel Saw
add: Added Auto Axe
add: Added Yao Guai Gauntlet
add: Added Storm Drum
add: Added Picket Fences magazine/skill book
add: Added SCAV! magazine/skill book (Issues 1-3)
add: Added Tribal Traditions recipe books
add: Added White Legs loadouts
add: Added Wayfarer loadouts
add: Added Sorrows loadouts
add: Added Dead Horses loadouts
add: Added Eighties loadouts
add: Added Rustwalkers loadouts
tweak: tweaked Yao Guai sprite
fix: always_available variable spelling in every file and instance
/:cl:

### CODE REVIEW

**Comment by OneOneThreeEight** [comment]
merge into master

**Comment by AsterixCodix** [comment]
> merge into master

All sorted!

**Comment by OneOneThreeEight** [comment]
Goddamn shitcoders that came before us with garbo english!

**Comment by OneOneThreeEight** [comment]
The 80s are bugged and only have north facing sprites.

**Comment by AsterixCodix** [comment]
> The 80s are bugged and only have north facing sprites.

Fixed, was initially a sprite mix-up

**Comment by AsterixCodix** [comment]
Any other changes required

**Comment by OneOneThreeEight** [comment]
nope! good to go

**Pull request merged**
