### PR TITLE
Test Loadout/Armory System (BoS)

### PR DESCRIPTION
**Pull request by Jawnner**
## About The Pull Request

Removes loadouts from standard BoS Paladin/Knight roles. Now their gear will be in the armory. Nuked Gauss/Minigun/Ripper loadouts. Removed Initiates/Knights starting with Gunsmith books, just pre-upgraded the BoS reloading bench with G&B books up to Part 3 along with some starting metal and gunpowder. Added ID-locked caste crates to the BoS armory along with re-doing the armory a bit. Armory was adjusted with ammo to compensate loss of loadouts, but senior roles/good RPers are expected to ration out said ammo instead of being shitters and taking everything.

StrongDMM_wBtOSG1kXe

**Paladin Crate**

2x tribeam laser rifle
2x r91 assault rifle
1x CZ53 minigun pack

**Knight Crate**

2x r93 assault rifle
2x wattz 2000 laser rifle
2x police shotgun

**Melee Shelf**

1x Super Sledge
2x ripper (no pre-war)

## Why It's Good For The Game

Loadouts for non-specialized roles is kind of ?????????. This was an idea frok pitched a couple of months back, and I was bored and had time today. I think this is better than the loadout system when it comes to the grunt roles. I want to extend this out to NCR/Legion/Oasis eventually, but BoS is easiest due to them not being in combat as the other three and it heavily affecting a round. 

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: BoS Caste Weapon Crates
del: Standard Paladin/Knight loadouts (loadout selector only has your Junior or full pins now)
tweak: BoS Armory
/:cl:

### CODE REVIEW

**Comment by OliOliOnsiPree** [comment]
I like this idea 👍 as it gives more a tad bit customization for regular paladins instead of the loadout having it under loadouts wise :)

**Comment by Jawnner** [comment]
My idea for Legion would be crates/lockers split across Recruit/Prime/Veteran levels. Want to eventually add more Legion explosives this way without breaking everything.

NCR Troopers/Combat Medic/Combat Engineer would share a crate/locker. Maybe Corporals/Sergeants having the same crate.

Splitting it between E3 and below, and E4 and above for NCR.

The grunt roles for each faction would be sharing ammo, and really only the special command roles would be starting with sidearms/ammo of their own on spawn.

**Comment by AllCorruptingWyrm** [comment]
I wish this could be applied to the other factions like NCR and the such
sadly can't though, unless I'm not thinking of it.

**Comment by Weaselburg** [comment]
I disagree with this for a variety of reasons.

First, I think the loadout system is simply better. Why? Because it actually lets you pick what you want - you don't have to hope someone took what you wanted and you're stuck with something you don't want, so it makes people latejoining more disadvantaged then they already are.

Two, gigantic problem when people inevitably matrix with one or more weapons. 

Three, it discourages individualism. Grunt roles having the choice of a loadout is, honestly, something that gives them more of a draw then weapons in crates or a singular loadout(which is how it used to be, and it was changed to this for a reason). By removing choice, for no real reason other then to remove choice, it makes people want to play those roles less.

Four, it removes AER9s for... nothing in particular that I can tell. Yes, I'm aware they can be made easily, but so can service rifles.

Five, cav loadout for Knights is fun and balanced. It's never tipped a fight in any way, and they're a fun thing for Knights to get for some more unconvential playstyle compared to all the other loadouts. While having base knight get pre-war ripper could be too much, yeah, senior could keep it, given how Senior and Head Paladin both get power fists.

Finally, if gauss rifle is being removed from standard paladin (which is mostly fine, honestly), it should be added to senior paladin.

I might come up with some more reasons later, but for now that's all I have.

**Comment by spackcorp** [comment]
counteractively I think the idea of this PR is great, can massively fix round by round faction balance by shifting weapons from roles to armouries meaning regardless of one faction lacking or having elite slots, they'd have equal access from the beginning to each tier of weapon in each quantity without any reliance on distribution via player population, though this may be out of scope of the PR. Honestly don't think access is particularly important, shitters will be shitters and they'll have access to guns regardless of what's done. Disagree entirely with weaselburg's point of 'disencourages individualism' as the concept of the PR overall encourages individual round by round supplying based on the available equipment in each stockpile, some randomising variables could also be considered given time.

**Comment by lolman360** [comment]
tribeam is a headpaladin tier weapon, having multiple roundstart is a bit much

**Comment by Weaselburg** [comment]
To be clear, I DO think it's something worth testing. Just that I have problems with it.

**Comment by Weaselburg** [comment]
Also, the book one and two going to knights is, iirc, meant to be because they're the gun makers of the BoS and the reloading bench not having the first two books was just someone being stupid. Given how other crafting roles start with book one and two(if I remember correctly) it's not a big deal. Even if they didn't it's just book one and book two.

**Comment by AdamElTablawy** [comment]
> I disagree with this for a variety of reasons.
> 
> First, I think the loadout system is simply better. Why? Because it actually lets you pick what you want - you don't have to hope someone took what you wanted and you're stuck with something you don't want, so it makes people latejoining more disadvantaged then they already are.
> 
> Two, gigantic problem when people inevitably matrix with one or more weapons.
> 
> Three, it discourages individualism. Grunt roles having the choice of a loadout is, honestly, something that gives them more of a draw then weapons in crates or a singular loadout(which is how it used to be, and it was changed to loadouts for a reason). By removing choice, for no real reason other then to remove choice, it makes people want to play those roles less.
> 
> Four, it removes AER9s for... nothing in particular that I can tell. Yes, I'm aware they can be made easily, but so can service rifles.
> 
> Five, cav loadout for Knights is fun and balanced. It's never tipped a fight in any way, and they're a fun thing for Knights to get for some more unconvential playstyle compared to all the other loadouts. While having base knight get pre-war ripper could be too much, yeah, senior could keep it, given how Senior and Head Paladin both get power fists.
> 
> Finally, if gauss rifle is being removed from standard paladin (which is mostly fine, honestly), it should be added to senior paladin.
> 
> I might come up with some more reasons later, but for now that's all I have.

The loadout system is going to die period. That's not up for debate.

Everything else is give or take.

**Comment by faaaay** [comment]
> The loadout system is going to die period. That's not up for debate.

source?

**Comment by ScheveningenZonn** [comment]
He made it the fuck up

**Comment by irakligabunia** [comment]
> > The loadout system is going to die period. That's not up for debate.
> 
> source?

my crackpipe

**Comment by AdamElTablawy** [comment]
> > The loadout system is going to die period. That's not up for debate.
> 
> source?

source i will force it

**Comment by Jawnner** [comment]
Just remove the faction.

**Pull request closed without merging**
