### PR TITLE
More NCR tweaks 🐒

### PR DESCRIPTION
**Pull request by spackorp**
## About The Pull Request

Removes needless slowdown from sergeant/ corporal armour (0.02 slowdown for 2(two) extra protection.. rlly bros?)
Adds an NCR flag item to LT (it's a gladius reskin for them to either use in melee, or give to someone to wave around)

## Why It's Good For The Game

Small changes that add flavour & playability

shoutout to stalkerino for asking & ahelping for it over the last 2 weeks

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [X] This code did not runtime during testing.
- [X] You documented all of your changes.

### CODE REVIEW

**Comment by cornercube** [comment]
the tiny boost in slowdown was to prevent the tiny increase in protection from being a straight upgrade
so at least on-paper there is a trade-off

**Comment by spackorp** [comment]
yeah no, 0.02 slowdown is not a 'tiny' amount, it's significant and noticeable. Whereas 2% protection increase is not by any means, would be understandable if the protection value mattered a little more (5-10%) but when compared to other armour in similar categories (recruit has 0,04 slowdown total. The only legion armour with 0,1 slowdown are vetdecan & centurion which have significantly higher armour values overall) the slowdown is a lot more relevant.

**Comment by spackorp** [comment]
when plating is fixed PFC armour will also be platable meaning it won't 'end up having 7 more protection' it will remain at 2, officers armours currently have significantly higher armour values with less slowdown, no one is complaining about those.

**Comment by Weaselburg** [comment]
> when plating is fixed PFC armour will also be platable meaning it won't 'end up having 7 more protection' it will remain at 2, officer armours currently have significantly higher armour values with less slowdown, no one is complaining about those.

I forgot that PFCs could plate.

**Pull request merged**
