### PR TITLE
deletes eigenstasium production reaction

### PR DESCRIPTION
**Pull request by zulixe**
## About The Pull Request

deletes the eigenstasium chemical recipe

## Why It's Good For The Game

bottom text

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by SeniorScore** [comment]
now this is epic

**Comment by somah69** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Review by Looreydev — COMMENTED** [review]
Necrotic code, etc. would be best to remove it completely, you can always [go back](https://git-scm.com/docs/git-revert) anyway.

**Comment by OneOneThreeEight** [comment]
agreed just delete it

**Pull request merged**
