### PR TITLE
Shop and salvaging update

### PR DESCRIPTION
**Pull request by qsef9999**
## About The Pull Request

This pull request is a buff to salvaging, doubling pre-war advanced salvage drop rate, and making it so anyone with a welder and mask can salvage. Additionally, the shopkeeper slots have been reduced to one.

## Why It's Good For The Game

The salvaging is so that anyone can reasonably craft guns. We've been filling bunkers with blueprints, now we need parts to craft them. And a lot of factions will just hoard blueprints even though they don't have a designated crafter. The shopkeeper, in all honesty, I'd like to add a shopkeeper assistant role to make up for it, but I don't know how. If someone else could PR that, it'd be great, but for now, I just hate butting heads with 2 shopkeepers all the time.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by zulixe** [comment]
no

**Comment by OneOneThreeEight** [comment]
**Doubling** yields is outright insane.

**Comment by companoo** [comment]
I removed two shopkeepers a while ago and somebody put it back in again

**Comment by BadAtThisGame302** [comment]
> I removed two shopkeepers a while ago and somebody put it back in again

Yeah because it was a bad change lol

**Pull request closed without merging**
