### PR TITLE
Currency Removals [WIP, awaiting discussion]

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

(Goofed previous branch, new PR.)
Effectively removes denarius, aureus, NCR dollars. Still available for admin spawn. Awaiting discussion on this, PR has only just been started, don't want to put too much effort in before people give feedback on the idea.

## Why It's Good For The Game

Our economy is terrible, these bloat cash types add absolutely nothing save for a tiny amount of flavour. They're either unused or converted into caps, and are best to be replaced entirely with caps so we've got a single stable currency for future improvements to economy.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
del: removed spawns for ncr dollar, denarius, aureus
w
/:cl:

### CODE REVIEW

**Comment by Jaaackx** [comment]
maps failing as spawners still present, will fix this after PR has been approved in concept + mapping freeze is lifted

**Comment by SeeminglyTypicalUsername** [comment]
Does anyone actually share this sentiment?

**Comment by Jaaackx** [comment]
> Does anyone actually share this sentiment?

quite a lot of agreement on the discord. if anyone's got a better idea then it's open but simplicity is best whilst we try and unfuck the economy.

**Comment by Malerus** [comment]
There's pushback for this change as the approach for "simplicity is better" is completely subjective, and rather than remove something that is meant to be flavorful, it should be approached to actually fix it and make it work.

**Comment by Jaaackx** [comment]
Closed.

**Pull request closed without merging**
