### PR TITLE
shield balance pass + tower shields + ACTUALLY kills linearmor

### PR DESCRIPTION
**Pull request by lolman360**
linearmor has been purged god bless

makes shields 10-15% more effective at absorbing damage across the board, and multiplies their health by 5. this should make them actually useful in more engagements.

adds tower shields, which slow while inhand and slow more when blocking, drain stam when blocking, have a high windup, but block an absurd amount of damage (60%)'

scrap tower shields are craftable by everyone, good tower shields are only craftable by people who get Scav!1 recipes

makes bashing generally more potent, by guaranteeing knockdowns on certain heavy shields (only legion/tower atm), increasing damage and stagger, and slightly reducing cooldown

'light' shields (currently only the bucklers) get a light shieldbash- no knockdown or knockback, but with a disarm

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

:cl:
del: linearmor for real
add: tower shields
balance: most shields
/:cl:

### CODE REVIEW

**Comment by VEN0M5** [comment]
Currently, actively blocking with shield already drain stam and halts stam regen. Not to mention the stam dmg you actually take when hit

**Comment by lolman360** [comment]
> Currently, actively blocking with shield already drain stam and halts stam regen. Not to mention the stam dmg you actually take when hit

intended, stam is a good balancing mechanic for shields otherwise you really only have protection/slowdown/integrity(which is less qol more cbt)

**Comment by ScheveningenZonn** [comment]
so fucking based.... i kneel...

**Comment by AllCorruptingWyrm** [comment]
I hope I can have epic anime duels with deathclaws after this

**Pull request merged**
