### PR TITLE
Replaces non-leader timelocks with universal playtime requirements

### PR DESCRIPTION
**Pull request by faaaay**
## About The Pull Request

Alters almost every role timelock to use EXP_TYPE_FALLOUT, meaning that they work off of _total time played_ rather than faction hours. Faction leader roles still use departmental timelocks. In this PR, roles are locked based on two things: the amount of complexity to them, and the power they hold over a round. 

Locks are as follows:
"Recruit" roles (Recruits, slaves) have no time requirement.
"Basic" roles (Your rank-and-file Primes, Troopers, Hunters) take 120 minutes. Initiates are also up here, due to the Brotherhood's Gamer Gear.
"Intermediate" roles (Corporals, Explorers, Knights/Scribes, Recruit Decani and other low-authority roles) require 300 minutes. Paladins are a special case; due to being heavily armed, they take 450 minutes.
"Advanced" roles (Sergeants, Senior BoS and the like; roles with some responsibility or authority) need 600 minutes.
"Command" roles (LT, Veteran Decanus) are locked to 900 minutes.
Faction leadership roles require 1500 minutes _in that faction_. Exceptions are BoS leaders - as there are three of them, so each has less responsibility - as well as Den/Tribe leaders as they are "minor" factions.

## Why It's Good For The Game

If you've played 15 hours in one faction, you almost certainly know enough to hop into any other. Right now, our timelocks are... a little unfriendly. If you want to play BoS or Tribal roles, you need to put in hours as a "recruit" role, even if you've got plenty of experience. If you want to play a Legion slave or a non-combat role, you need to spend time as a combatant role you may have no interest in.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: replaced all non-leader role timelocks with non-faction-specific locks
/:cl:

### CODE REVIEW

**Review by OneOneThreeEight — CHANGES_REQUESTED** [review]
Lower the leadership hour requirement down to 100 hours or so per faction. I think that seems much more fair given the circumstances. 1500 hours is a TF2 NEET level number but not practical for our purposes.

**Comment by faaaay** [comment]
> Lower the leadership hour requirement down to 100 hours or so per faction. I think that seems much more fair given the circumstances. 1500 hours is a TF2 NEET level number but not practical for our purposes.
> 
> Unless you meant 1500 minutes LMFAO

Yes, exp requirements are in minutes- oh wait, yeah, I did mistype that in the PR body.

**Review by OneOneThreeEight — APPROVED** [review]
this is fine, then, miscommunication!

**Comment by buffyuwu** [comment]
i'm not sure i want to see people joining factions with no experience into roles and ranks that matter. the initiate/recruit system seems to work fine and forces the player to learn the role before being expected to perform within it.

**Comment by cornercube** [comment]
> i'm not sure i want to see people joining factions with no experience into roles and ranks that matter. the initiate/recruit system seems to work fine and forces the player to learn the role before being expected to perform within it at a normal/higher rank.

5 hours of initiate to play knight or scribe is way too excessive, though
2 hours of recruit to play prime legionary is fine

**Comment by faaaay** [comment]
> i'm not sure i want to see people joining factions with no experience into roles and ranks that matter. the initiate/recruit system seems to work fine and forces the player to learn the role before being expected to perform within it at a normal/higher rank.

But what experience is needed for a non-recruit role? Take Knight, for example. Almost everything you'd be asked to do - salvaging, scouting, fighting, setting up defences - is done in most other factions anyway, and is something you'd pick up by then.

**Comment by OneOneThreeEight** [comment]
Recruit tier to standard rank should usually be 2-3 hours of playtime imo.

**Comment by faaaay** [comment]
> Recruit tier to standard rank should usually be 2-3 hours of playtime imo.

That'd be the case with this PR (with the exception of BoS).

**Comment by Pebblesthe2nd** [comment]
The logic behind forcing you to play recruit for one or two hours before doing slave was to reduce the amount of no-effort idiots who immediatly join as slave and just act like antags, not knowing a single thing about what Legion really should be, and not bothering to read the short spawn in text for guidelines.

You should have a grasp of the core experience of a faction before doing peripheral stuff (core for legion being recruit/warrior first, as NCR trooper, as Follower a pink-haired futa snowflake OC powergaming in some corner. It helps you know whats actually useful as non combat roles in a faction too.)

Huge timelocks are pointless though and should be remedied. Good luck.

**Comment by faaaay** [comment]
> You should have a grasp of the core experience of a faction before doing peripheral stuff (core for legion being recruit/warrior first, as NCR trooper, as Follower a pink-haired futa snowflake OC powergaming in some corner. It helps you know whats actually useful as non combat roles in a faction too.)

I can certainly see where you're coming from. It's good to make sure you know at least a _little_ about the faction you're in.
With that said, I still believe that a universal timelock can potentially achieve this. If you've sunk a couple of hours into the NCR, you've likely gathered at least the _basic_ info about the Legion, and shown you're not here to be a shitter.

Maybe it'd be worth testmerging the PR first to see if it affects the quality of play.

**Comment by buffyuwu** [comment]
>  as Follower a **pink-haired futa snowflake OC** powergaming in some corner.

hey pebbles do u mind Not posting stuff like this thanks

**Comment by Pebblesthe2nd** [comment]
> > as Follower a **pink-haired futa snowflake OC** powergaming in some corner.
> 
> hey @Pebblesthe2nd do u mind Not posting stuff like this thanks

For you, anything!

**Comment by buffyuwu** [comment]
yeah i can't justify this because it would lower the quality of factions

**Pull request closed without merging**
