### PR TITLE
fortnite nerf (removes unsupported lattice building)

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request
removes unsupported lattice building. all lattice must be supported by wall underneath.

## Why It's Good For The Game

No More Fortnite 

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
balance: lattices now need support
/:cl:

### CODE REVIEW

**Comment by SeniorScore** [comment]
INCREDIBLY unbased.

**Comment by lolman360** [comment]
> INCREDIBLY unbased.

schev wanted it im sorry

**Comment by Kneesox44** [comment]
Is it possible to work this so that they can only go a limited distance unsupported? Latticing across two-three tile gaps seems fine and dandy, it's just people building fort-nite skybases across entire desert plains that is raising eyebrows.

**Comment by AllCorruptingWyrm** [comment]
FORT NITE!!!


can we get a gif to show how it works exactly?

**Review by Looreydev — APPROVED** [review]

**Comment by Jaaackx** [comment]
> Is it possible to work this so that they can only go a limited distance unsupported? Latticing across two-three tile gaps seems fine and dandy, it's just people building fort-nite skybases across entire desert plains that is raising eyebrows.

100% this, we should not stop people moving across 1/2 wide gaps, try to check for a wall on the layer below?

**Comment by lolman360** [comment]
limited distance unsupported fix pushed, now checks for walls in a 5-tile radius

**Comment by AdamElTablawy** [comment]
unnecessary

simply make falling break bones and it will remove the abusability of fortnite while keeping the comedy factor so that we don't lose entertaining features

**Pull request merged**
