### PR TITLE
Possibly makes IDs no longer burn?

### PR DESCRIPTION
**Pull request by xPokee**
## About The Pull Request

I made this out of frustration after losing my ID from burning to death.

## Why It's Good For The Game

Nobody else will lose their ID by burning to death.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
fix: fixed a few things
/:cl:

### CODE REVIEW

**Comment by Kapu1178** [comment]
Why not just define this on the `/id/` parent type

**Comment by xPokee** [comment]
> Why not just define this on the `/id/` parent type
I'll be honest chief, I'm fairly new to coding.

**Review by OneOneThreeEight — CHANGES_REQUESTED** [review]
Yeah, just define this through /obj/item/card/id/ so that all derivatives of an ID will automatically inherit the behavior.  There's no reason for every child path to have the exact same resistance flags.

**Comment by OneOneThreeEight** [comment]
Okay, then.

**Pull request closed without merging**
