### PR TITLE
Brotherhood Faction Armour

### PR DESCRIPTION
**Pull request by AsterixCodix**
## About The Pull Request

Adds in Brotherhood faction power armour, (see below for a preview, and to review them).

image
image

After some feedback, the sigils have been darkened down slightly, to better blend with the armour.

Also adjusts the Brotherhood's combat armour somewhat to give it a bluish hue.

image
image
image
image

## Why It's Good For The Game

The Brotherhood now conforms to the rules on faction armours

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Brotherhood T-51b
add: Brotherhood T-45d
tweak: Brotherhood combat armours
/:cl:

### CODE REVIEW

**Comment by UntoldTactics** [comment]
Note that you'll need to replace the paladins spawn PA with /obj/item/clothing/suit/armor/f13/power_armor/t45d/bos otherwise they just spawn with regular t45d

**Comment by BadAtThisGame302** [comment]
Might I suggest a change of color from blue to Green on the combat armor? (Keep it true to Fallout)

**Comment by AsterixCodix** [comment]
> 

Yeah, was a slight oversight. Perks of coding it in at 3am

**Comment by AsterixCodix** [comment]
Latest commit just makes the helmet icons the same colour as the on-mob sprites

**Pull request merged**
