### PR TITLE
The Ensmartening of Tribals

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

Removes Trapper as a default quirk for tribals, replaces it with Technophreak. Adds Trapper as a trait they can select from the book. **Literally just switches 1 default trait and 1 selectable trait.**

## Why It's Good For The Game

Tribals in Fallout are not exclusively **unga bunga hit rock with rock smash uuuuuuuuuuuuugh** cavemen, most are just people with unusual cultures and most use guns/technology. This just separates them a little from the Wayfarer LIGHT SMASH BAD MACHINESPIRITIS I HATE SAAI F CUKING HATE LIGHTS THEY MAKE ME SUCPO FUCKIGNE MAD cringe of old.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
tweak: switched a trait around
/:cl:

### CODE REVIEW

**Comment by SeniorScore** [comment]
literally fucking what. Tribals needed to be tweaked sure but what in the God damn is this even trying to do. ALL tribals don't need technophreak

**Comment by OneOneThreeEight** [comment]
be aware technophreak massively boosts salvage return trait. i would consider just removing some of the attributes to tribals that arbitrarily make them technophobic instead

**Comment by Weaselburg** [comment]
This doesn't really make any sense. Technophreak doesn't let you use machines, it gives you more/better salvage. Trapper being removed also doesn't make all that much sense - what's the reasoning on that? It doesn't affect PvP, or PvE, and lets them actually make things from the tribal crafting menu.

**Comment by Jaaackx** [comment]
Mistake on my behalf, I was under the impression TECHNOPREAK let people use autolathes.

Will rework or remove the TRIBAL trait that deals with tech and adjust when I am home.

**Comment by Weaselburg** [comment]
> 

That's understandable. I believe the machine spirit trait is the one that overrides it if you don't want to remove it outright, and it also lets them use the chemistry table thing they can make, if I recall correctly..

**Comment by Jaaackx** [comment]
taking down this PR because tribals can ALREADY USE TECH? I was misled........................................................................................................................... society................................................................................................
Will make new PR altering formal tribal trait + changing these quirks more.

**Pull request closed without merging**
