### PR TITLE
Followers Test Exodus/Town Doctor

### PR DESCRIPTION
**Pull request by Jawnner**
## About The Pull Request

Cont'd from this: https://github.com/LoneStarF13/LoneStar/pull/364

**Followers**

Oasis decided that the Followers could cause too much damage to town relationships due to their own agenda (Mainly Legion aggression) so they kicked them out. However, thanks to contacts in the Brotherhood of Steel and New California Republic, they have been able to safely move to the clinic north of the old Vault-Tec Museum. While losing a couple of volunteers and some doctors who decided to stay in the town and be apart of the clinic, they have bolstered their security force and equipment.

+2 Followers Guard slots, along with three different loadouts. Worn-out old assault carbines from their NCR buddies, police shotguns from some key friends in Oasis, and even AEP7 pistols from the good old Brotherhood of Steel. Due to the exodus, the Followers have even begun to pay more for experienced wastelanders and even former outlaws/raiders to bolster security. These guys are even pros at disassembling pre-war salvage (Technophreak).

-1  Volunteers/Doctors. They decided to stay within Oasis walls. Sad.

Administrator untouched.

Reborn Clinic: Thanks to some of the new guards, and administrators using teachings of former personnel (NCR), they were able to quickly set-up fortifications outside the clinic. (First test of pre-built fortifications which should become the standard tbh.)

StrongDMM_qY4o7k3Ekq

StrongDMM_B0cttem3n8

**Oasis**

+2 Doctors. These guys are pretty good doctors for wastelanders. Some are former Followers, some are former combat medics from wherever they came from. However, the town of Oasis isn't the most advanced. Some say due to how stingy the shopkeeper, the doctor's office isn't as advanced. However, citizens came together and were able to procure some chemistry machines (I might add in a heater, but I wanted to have tiers of medical capabilities in the wasteland). However, the shopkeeper wasn't all too bad, having a contact in the NCR, they were able to get some of those advanced sutures and meshes that the Rangers use in the field. 

StrongDMM_nLIPWOut0i

## Why It's Good For The Game

Followers and Oasis finally seperated, Followers can be a decent military force (I might add in another guard slot tbh, want to get feedback.) Decent-tech town doctor is cool, going for a Doc Mitchell NV type vibe. 

Followers Guard won't get absolutely bullied early and can hold their own and then some.

Loss of plant setups was to encourage more scavenging (getting planters is trivial)/interaction with Oasis Farmer who was pretty much reduced to a fluff role because they weren't needed.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Oasis Doctor's Office
add: Followers Clinic north of Vault-Tec Museum
del: Followers bunker (cave-in)
tweak: Followers Guard loadouts
/:cl:

### CODE REVIEW

**Comment by Snoozer000** [comment]
What's the plan about the botany setups? is that removed for both?

**Comment by PraxisApricotte** [comment]
Why was this opened again? I thought we have already explained why moving Followers, an organization known for integrating itself into communities, is a bad idea.

**Comment by AllCorruptingWyrm** [comment]
... And so will Oasis doctors?

Oasis doctors will genuinely be Followers but without morals, watch it.

**Comment by AllCorruptingWyrm** [comment]
> I personally can't think of a good reason to do this, 'Town Doctor' is a redundant role as long as the followers exist, and I highly doubt the followers will be removed anytime soon.

No, what's going to happen is that Town Doctor will be for crazies and cause nothing but mutagen incidents or they'll be le generic quirky wasteland doctor #211-5. It's going to be Den Doctor but worse "but it's gonna be better this time!!!" at least with Den Doctor, they revived raiders and had a niche.

**Comment by AdamElTablawy** [comment]
> > Why was this opened again? I thought we have already explained why moving Followers, an organization known for integrating itself into communities, is a bad idea.
> 
> They have too much passive influence over the town.

worthless comment

anyway @Jawnner go ahead and close this, this idea has been tried before and failed horribly

you cannot fix the followers/medicine/medical situation no matter what you do or what you try so there's no point bothering at all

**Comment by SeeminglyTypicalUsername** [comment]
> > > I personally can't think of a good reason to do this, 'Town Doctor' is a redundant role as long as the followers exist, and I highly doubt the followers will be removed anytime soon.
> > 
> > 
> > No, what's going to happen is that Town Doctor will be for crazies and cause nothing but mutagen incidents or they'll be le generic quirky wasteland doctor #211-5. It's going to be Den Doctor but worse "but it's gonna be better this time!!!" at least with Den Doctor, they revived raiders and had a niche.
> 
> Actually, addendum here because I do not want to come off as disingenuous or anything of the sort but, if THAT IS what we want then, by all means, I support it, I simply want to highlight that I, personally, feel like this is going to end up like a Den Doctor situation, without any real direction this time. See, Den doctor dealt with criminals, Oasis doctor and Followers wouldn't in this situation, unless at gun point, that is.

Why wouldn't the the town doctors treat criminals?

**Comment by AllCorruptingWyrm** [comment]
>Why wouldn't the the town doctors treat criminals?

Because why would you kick out your doctor? This is exactly the passive influence medics would have over the town here.

**Comment by SeeminglyTypicalUsername** [comment]
> > Why wouldn't the the town doctors treat criminals?
> 
> Because why would you kick out your doctor? This is exactly the passive influence medics would have over the town here.

What does that have to do with them refusing to treat people?

**Pull request closed without merging**
