### PR TITLE
med-sci treasure: science is its own reward

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request
adds a special spawner intended to replace guns as loot
gives some funny tech for the BoS to find

loot of note: 
mid-surgery granter
box of deluxe parts
FEV (at a far lower spawn rate than anything else on the list)
janitor implant
NVGs
meta beaker
the needler

split into mid and good spawners 
the drug spawner is the low variant

## Why It's Good For The Game
dumb stuff that doesnt make people sideways (except the needler)

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
add: 2 new spawners with medical theming
/:cl:

### CODE REVIEW

**Comment by VEN0M5** [comment]
> so i know bos can make nvgs but thats something nice for other groups. Honestly alot of this sounds nice things instead of weapons to get

BoS cannot make NVGs. I only know head scribe spawns with one, not sure about the other heads.

**Comment by Snoozer000** [comment]
More craft and tool loot is always a plus. As far as I know there is like a single deluxe box spawn. nvgs I think two?

**Comment by VEN0M5** [comment]
> More craft and tool loot is always a plus. As far as I know there is like a single deluxe box spawn. nvgs I think two?

3 NVG spawns... But they are RNG medical item spawns. You either get Med NVG, combat deflib or combat stimulant injector

**Comment by Snoozer000** [comment]
> > More craft and tool loot is always a plus. As far as I know there is like a single deluxe box spawn. nvgs I think two?
> 
> 3 NVG spawns... But they are RNG medical item spawns. You either get Med NVG, combat deflib or combat stimulant injector

I know of like 2.

**Pull request merged**
