### PR TITLE
multi-z shit, areas fix included

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

mapping for multi-z

gifs of changes, files too big for Git: https://imgur.com/a/LyhUuKD (this is bulk of changes but some were updated)

added a 2nd level to a random building north of Oasis

added a 2nd level to the north and south gates of oasis, with buttons to control gates

corrected all areas on the upper z-level so weather and stuff functions correctly on rooftops

moved a random building in the legion up a z level and added stairs, also 2 watchtowers.

added walls around the legion on the upper z level so they're actually protected from sky catwalk raids

## Why It's Good For The Game

because multi-z is awesome

## Pre-Merge Checklist

- [y] You tested this on a local server.
- [y] This code did not runtime during testing.
- [y] You documented all of your changes.

## Changelog

:cl:
tweak: map for multi-z
/:cl:

### CODE REVIEW

**Comment by Weaselburg** [comment]
Why does the legion need two watchtowers? It could work, but where are they placed? They already have the police station second z-level so having THREE z-level entrances could end up being weird.

**Comment by SeniorScore** [comment]
> Why does the legion need two watchtowers? It could work, but where are they placed? They already have the police station second z-level so having THREE z-level entrances could end up being weird.

I'd argue its just as much a liability

**Comment by Jaaackx** [comment]
one on gate, one in the centre of camp
StrongDMM_Oodw61wQnF
.

**Comment by Jaaackx** [comment]
i lied, the stairs don't work, DNM, need to fix

**Comment by Jaaackx** [comment]
this fixed now, ok to merge

**Pull request merged**
