### PR TITLE
Bombs grenades bugfixes rocket launchers & pre war alloy

### PR DESCRIPTION
**Pull request by AdamElTablawy**
The long awaited.

So basically, this adds crafting grenades of all kinds-the kinds I added earlier, specifically.

Under the purchaseable/common skillbook (Forgemasters and LOs get this by default, the NCR minelayer engineer loadout which was underpowered can also get this, blastmaster raiders get this by default, it's purchaseable from vendors or findable in loot piles for skillbooks)

Landmines (already existed)
Fragmentation grenades
Smoke bombs
Flashbangs
Stingbangs
Rocket casing
Low-yield HE rocket (you still need to find the rocket launcher)
Under the rare skillbook (you have to find this, other implementations are up in the air, it can be acceptable dungeon loot)

EMP grenades
Incendiary grenades
HHE rockets
Incendiary Rockets
Radiation grenade
Concussion grenades
Not craftable, only lootable:

C4
X4
Plasma grenades
Chemical warhead rockets
New to loot piles:

Break-action grenade launchers (high tier, projectile half as fast as bullets, 5% spawn chance, takes a40mm grenades which do 5 direct damage and cause a light explosion on hit, a40mm grenades are uncraftable but lootable (we can make this available to legion without much problem, but i'm holding off on that right now)
Rocket launchers (ultrahigh tier like bozars, rare chance to spawn)
All rocket types
New grenade spawners from tier one to four (top tier), which mappers can use
Penetrator a50mg rounds for the AMR, added earlier by me, never spawned
Rocket launchers are a purely PVP weapon and useless in PvE. Thanks to my earlier explosive changes, none of these should oneshot.

LHE rockets, the 'common' ammunition for the rocket launcher, will hurt, but won't even significantly slow someone down in heavy armor.

HHE rockets will absolutely send someone flying and beat the shit out of them, and are good crowd control OR for smashing a hole in defenses. Fortunately, they are expensive to produce.

Incendiary rockets will set a large portion of people in range on fire. They excel at crowd control, but cannot break defenses. Still, firing one of these into a crowd and having it hit will lead to instant panic and mass chao.

Chemical rockets are a lot like incendiary rockets. It kills relatively quickly, but can be partially negated by taking the rad-x everyone starts with (aside from legion, who are shit out of luck, wear your masks). They are also ONLY lootable.

I have also added a raider loadout that was added but accidentally left unimplemented (the cannibal) and removed the bulk of kelo's unused and terrible guncrafting bloat code.

Pre-war alloy is now obtainable via the ORM, using Lead, Plasma, and Titanium. Lead can be mined or obtained from salvage, as can titanium (as well as hq metal parts, which are titanium.)

I tweaked the raw damage of explosives some further. They're somewhat weaker (in theory four points, in practice on multitiles up to 11) and do less stamina. 

## Why It's Good For The Game

nokia ringtone

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

proof:

https://user-images.githubusercontent.com/16738319/148471780-9c421fea-8738-4752-85c4-c0156ceed43d.mp4

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
oh GOD what the FUCK happened to the video?

**Comment by AdamElTablawy** [comment]
image

https://user-images.githubusercontent.com/16738319/148475106-6676d632-44f7-4ec4-b79a-bbb42f6e7673.mp4

**Comment by AdamElTablawy** [comment]
image

**Comment by Neveralone1744** [comment]
Grenade spears! rustwalkers "witness me!" XD

**Pull request merged**
