### PR TITLE
BRINGS BACK THE FLIP EMOTE

### PR DESCRIPTION
**Pull request by AdamElTablawy**
FINALLY

THE MOST IMPORTANT PR

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by buffyuwu** [comment]
ok this made me laugh but im willing to add it on the condition that you make it consume stamina to flip

**Comment by AdamElTablawy** [comment]
ok

**Comment by AdamElTablawy** [comment]
done

**Comment by AdamElTablawy** [comment]
wait, i'm an idiot one second

**Pull request merged**
