### PR TITLE
Loadout changes, misc issues fix, tribeam "buff", removed neostead, ALR, and Wattz2k from HK.

### PR DESCRIPTION
**Pull request by Cythisiax**
Tested

Neostead > RCW
ALR15 > G11
WATT2K > Tribeam

Tribeam got .1 penetration applied to hitscan. Still incredibly shit and useless.
Fixed Khan radio desc. issue.
Fixed big_leagues trait issue.
Fixed "Desert Combat Boots" Non-sprite issue. Made "laced" icon_state

Nerfed G11, making it unattachable. Added 4 spread and .1 recoil similar to XL70E, but worse fire_rate.
Gave all paladins AER12, removed AER9.
Ballistic minigun pending nerf in comparison to gatling laser.

### CODE REVIEW

**Comment by Cythisiax** [comment]
Ah fucking TMs are an actual pain not letting me PR to the main branch because of merge conflicts.

**Comment by Cythisiax** [comment]
Reverted .1 pen due to merge conf.

**Comment by Jawnner** [comment]
Paladins don't need AER12, literally stop. ALR15 just needs some love, not getting replaced with the G11. HK doesn't need an RCW or a Tribeam.

**Comment by Cythisiax** [comment]
ALR is literally a Bozar or XL70E
G11 is actually harder to maintain due to the ammo requirement, the 50 bullet can be reduced entirely.
ALR is also not canonical at all and is a donator-made weapon that has no purpose of being here, "AR15s" Were never in fallout.

RCW is nothing special, and can easily replace the Neostead or WattZ2K. Wattz2K is arguably an AER14 with wounding.

**Pull request closed without merging**
