### PR TITLE
Properly organized crafting menu

### PR DESCRIPTION
**Pull request by XElectricX**
## About The Pull Request

The crafting menu should be taken out and shot but it's the only way I see multi-ingredient recipes being easy to implement so may as well make it easier to use and add to.

Main changes:
- Move items to their proper groups
- Alphabetical order of recipes within their own relevant subgroups
- Remove duplicates and any bloat (a file dedicated to like 5 egg recipes, come on son)
- Spelling mistakes, renaming of things to be more uniform, standardize tab spaces to have neater files
- Small changes to recipes like correct ingredients

Changes to foods and their recipes:
- Removed the "Foods" title that every food category title had (why did it exist?)
- Remove Mexican category because it's bloat and mildly racist
- Renamed Food Wasteland category to Frontier Food, will change if anyone can find a better name than "poor people food"
- Removed egg-based recipes file, moved to misc foods file
- Added Sweets category
- Pies & Sweets is now just Pies
- Renamed Soups to Soups & Stews
- All soups need 20 water, stews need 10 water, and the weird jelly things need 5 water
- Stew changed to beef stew, only needs cutlets, potatoes, and carrots.
- Fuego plasma burrito changed to fuego bean burrito, made from soybeans, cutlets, and chili
- Raw khinkali no longer uses garlic, needs pepper and onion instead; garlic is apparently a Russian derivative
- Carne de asada burrito changed to carne asada burrito; this is the correct name
- Moved a lot of recipes around to the categories they actually belong to
- Readded a bunch of recipes that were commented out

Recipes standardized to use the following structure:
image
Recipe path name matches `name` and does not use underscores. As is it seemed to be the standard already, changed all `name` strings to only have the first letter capitalized. The `reqs` list is all one tab space under it, including the closing parentheses.

Much more to come.

## Why It's Good For The Game

Ease ~~my~~ the suffering of players and contributors.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [X] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by XElectricX** [comment]
For some reason the UI breaks on local client and so I can't access the crafting menu ingame for testing. Suggestions to fix this would be nice.

**Comment by BadIsMyUsername** [comment]
> For some reason the UI breaks on local client and so I can't access the crafting menu ingame for testing. Suggestions to fix this would be nice.

Click on the checks tab and then on the checks themselves to see what is wrong. Most of them provide a little hint in their log as to what went wrong, very handy for fixing said issues. For example, this is what I can see in the logs of your checks:
> code/modules/food_and_drinks/food/snacks_meat.dm:321:error: /datum/reagent/consumable/pepper: undefined type path
> code/modules/food_and_drinks/food/snacks_meat.dm:330:error: /datum/reagent/consumable/pepper: undefined type path
> file ./code/modules/food_and_drinks/recipes/tablecraft/recipes_misc.dm is missing a trailing newline file
> ./code/modules/food_and_drinks/recipes/tablecraft/recipes_sweets.dm is missing a trailing newline

Hope this helps! :)

**Comment by Pebblesthe2nd** [comment]
The TGUI crafting menu is black magic, I know, I have done similar sorting once long ago. What I found in testing was adding new categories/subcategories or even adding recipes to certain categories caused bluescreen for no apparent reason. The only way I discovered to find out the limit is to test locally over and over, tedious as hell, adding a batch of recipes at a time and seeing when it breaks.

In effect, what worked for me was stepping back to the unchanged version of the crafting structure, then adding/removing stuff in chunks, then testing, and so on. I know of no other way.

Crafting menu needs heavy revising, it's a disaster. I've considered both moving all clothing stuff to inhands, and making most of the food things go into a handful of books easily available, but its on hold for the moment, whatever improvements that can be made can be built from until we get less suicidally messy crafting,.

The principle being crafting menu should be default filled with 
*stuff thats actually important/useful (fluff stuff kept to 1-3 categories clearly labeled as such is fine)
*stuff that most players will want access too
*as few things as possible, the current mess makes it hell to find stuff for no good reason. Marginal stuff should be moved to things like benches and tool crafting, or locked to books thats easy to find.  
*with less stuff crammed in there better labeling is possible to further reduce the agony. More specific labels, fewer items in each category.

Seems your ideas are fairly in line with these principles so have at it I say, just remember to keep branch up to date etc, good luck.

**Comment by XElectricX** [comment]
I have been trying to read the checks thing, I know it's not the error'ed paths because I added those in hastily at the end to get something through. Stuff was compiling fine, just local UI not working. Had to use the old UI to even see chat but windows stopped working.

> I've considered both moving all clothing stuff to inhands, and making most of the food things go into a handful of books easily available

Originally I was going to remove the craft menu and move it all to inhands or machines, but then I thought about how the crafting menu is the easiest way to facilitate relatively simple recipes like furniture and food. Unlike sheet-based recipes, it allows users to use more than one ingredient and set requirements, so it has that going for it. I don't know what you mean by books, unless you're talking about skill books that grant food recipes, but I have no idea how learned recipes are handled as there is nothing I see attached them apart from that `available` variable.

**Pull request closed without merging**
