### PR TITLE
remove lifegiver from tribal book (done)

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

because +health quirk is dumb

edit: also renames tribal quirks upon request into generic ones

## Why It's Good For The Game

title

**EDIT**:

_Apparently '_because +health quirk is dumb_' wasn't enough so, reason for the Lifegiver removal:_

Tribal is no longer a melee role. White Legs are able to use guns, Sorrows are able to use guns, Dead Horses are able to use guns, Rustwalkers are able to use guns, Eighties are able to use guns.

A 10% health advantage over other roles without Lifebringer (the vast majority of roles, including those tribal is most likely to be competing for loot with) is unfair and encourages powergaming. It is the **obvious, universally useful choice** for anyone wanting to do PvE or PvP.

The only other roles with Lifebringer available are the Sheriff, Head Paladin, Captain, Vet Ranger, Centurion, Decanus Roles, Vexillarius and Veteran Legionnaire. These are all specifically **hardened combat roles**. Tribal is not, it is a generic Wastelander-style role. I am not a fan of those combat roles having it either, but the tribal quirks were a recent change and will not affect the balance of faction v faction combat.

It should never have been given this quirk, and there is no reason for them to keep it. **This PR is not replacing it with anything, seeing as that keeps coming up....**

## Pre-Merge Checklist

- [y] You tested this on a local server.
- [y] This code did not runtime during testing.
- [y] You documented all of your changes.

## Changelog

:cl:
del: lifegiver from tribal book
tweak: tribal quirk names and descs
del: wayfarer trait book selection option that gave no quirk
/:cl:

### CODE REVIEW

**Comment by OneOneThreeEight** [comment]
some other thoughts, actually. could you make the books and their descriptors renamed to specific tribal 'flavors' of what the abilities are? maybe a white leg doesnt want big leagues but wants something else while still picking one of the whiteleg outfits.

**Comment by Snoozer000** [comment]
Why remove? What are we replacing it with? Just because something is dumb doesnt mean it should be tossed out with the babies water. If they get nothing in return I would say no. Especially as most tribals are melee brawlers and need the health. You hardly see them use bows/javalins.

**Comment by AllCorruptingWyrm** [comment]
A prime example of why we shouldn't remove something and instead, we should replace it with something that encourages a gameplay loop.

**Comment by Jaaackx** [comment]
@OneOneThreeEight Will do, will make the traits generic rather than tribe named.

@Snoozer000 Because Lifegiver is a quirk that never should have been given to a generic waster role. If you want more health, find better armour.

@AllCorruptingWyrm This makes no sense whatsoever. This is a quirk and has absolutely nothing to do with _gameplay loops_??

**Comment by Jaaackx** [comment]
@OneOneThreeEight tested and ready if you are happy with trait names. removed the wayfarer one because it didn't give any quirk whatsoever.

**Comment by Snoozer000** [comment]
> Because Lifegiver is a quirk that never should have been given to a generic waster role. If you want more health, find better armour.

a lot of roles are generic. Pretty much all roles are generic except for the main factions.

They also wont dress tribal then. pretty much all the tribal armors are light. They need it for speed because there main gameplay loop is fighting deathclaws in places with obstacle and slowdowns. Whats the point of better armor when a deathclaw COMPLETELY negates this by directly shredding your cloths. Once your cloths are gone IIRC your armor falls off too. You cant cade against deathclaws and you really cant tank against deathclaws. You need speed and health. I think the only exception would be wayfarers with tribal combat/pa armor. But odds are high the only way they are seeing that armor is fighting deathclaws anyways. There really isnt any other way for a wayfarer to have access to those armors. That is also only one tribe. Sorrows have the lightest armor. I think the heaviest would be either whitelegs or rustwalkers. Most tribals fight in there spawn armor and dont have a mechanism to upgrade their armor like other factions. They cant strip armors for plates and they cant attach plates to their armor. I think the only tribe with a clear direction of armor upgrade would be rustwalkers. Light, medium, than you combine them for heavy rustwalker. No tribal has good head armor.

a small health boost for a subfaction the almost exclusively uses melee makes sense. once again. If you plan on replacing it with another perk im listening. A trait nerf for no reason other than:



> +health quirk is dumb

Is not sufficient. 

also why are you complaining about tribals being generic waster roles when you are attempting to make them more generic.
        var/list/choices = list("White Legs","Rustwalkers","Dead Horses","Sorrows","Eighties","Wayfarers","Other")
	var/list/choices = list("Hit Them With Sticks","Technophilia","Pugilist","Padded Feet","Veteran Table Climber")

**Comment by Jaaackx** [comment]
not gonna sit and argue about a quirk, host can decide.

host requested the quirks be made generic.

**Comment by Neveralone1744** [comment]
i will also state that this is very odd to do, and their argument is valid. Tribals are getting diverse and have some semblance and starting point with the name sorrows dead horses etc. while the other just makes them ever closer to becoming generic with no real way besides meta to really group up besides walking up to people your character does not know and just going, "hey want to be a tribe?" which again makes no sense. on the lifegiver i really don't see why at the very least you wouldn't replace it with something else. have you played tribal before?

**Comment by Jaaackx** [comment]
The renaming of the quirks makes sense. A person picking the 'Eighties' loadout shouldn't feel pressured to take the corresponding 'Eighties' quirk (freerunning), which is absolutely useless.

I will update the PR with better reasoning for the Lifegiver removal and will allow Schev to decide.

**Comment by Neveralone1744** [comment]
ehh those perks are just simply perks that fit the style of that tribe. honestly what im talking more about is what are you replacing life giver with?

**Comment by AsterixCodix** [comment]
So, to break down why the quirks were listed with the names of each tribe:

They're intended to be things that everyone in that tribe would know. Things like the Rustwalkers having the Technophreak perk and a set of crafting recipes that revolve around scavenging (the shovel not withstanding), or the White Legs having the crafting recipes for basic firearms and Big Leagues, because they were taught to fight by the Legion, and have the basic knowledge of weaponry because they raided an old armoury. 

The traits lined up with the identity of their respective tribe, with a fairly generic trait that rarely actually gets picked for the generic option (because, holy crap there are a lotta tribes and there's no way in hell I'm making crap for all of them). Renaming the perks kinda just... Makes them completely generic and undermines the whole thing of a "Tribal Identity", of a particular group with a particular way of life that they pass down through the generations. 

The Wayfarers one not giving a perk? Yeahhh, that was an oversight. The 80s having Freerunning? Yeahhh, when every tribe gets Hard Yards, the hell could the fast moving tribe get. Dead Horses having Iron Fist and the White Legs getting Big Leagues, was quite honestly me writing the code at 3 am and getting them the wrong way round when translating my notes into this Frankensteinian amalgamation we call a programming language

Just my tuppence on this and an explanation as to why this crap was made the way it was.

**Comment by Jaaackx** [comment]
It's just unnecessary confusion. You shouldn't need to code dive or test each one to tell what specific quirks do, and all tribal roles get the trait selection. I get the idea, but the loadouts are enough for tribe specific flavour.

**Comment by Jaaackx** [comment]
Closing this PR and making a new one, doing a full balance pass through the tribal roles.

**Pull request closed without merging**
