### PR TITLE
gives elevator a movement delay

### PR DESCRIPTION
**Pull request by AdamElTablawy**
this SHOULD work but if it breaks just untestmerge it

it works on my thing but my thing has a broken UI

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by buffyuwu** [comment]
interesting

**Comment by buffyuwu** [comment]
im sure pots will yell at me if this starts killing people and/or leaves them stranded on a floor when this is TMd

**Comment by AdamElTablawy** [comment]
do not merge until bard’s stuff works

**Comment by buffyuwu** [comment]
yea im fixing this junk so ill close this for you dw thanks

**Pull request closed without merging**
