### PR TITLE
New NCR Base

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

New NCR Base
image

## Why It's Good For The Game

Better base than the current one

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: Tweaked the NCR Base
/:cl:

### CODE REVIEW

**Comment by BadAtThisGame302** [comment]
This new map includes every NCR Rank by the way, so it's OK to merge whenever and not wait for a role reduction PR.

**Comment by Sinbest** [comment]
Terrible, please do not merge and please un-test merge

1. It has several mistakes such as the defib being too far from the operating table in the tiny shitty medical room.\
2. It's poorly planned, every room is too small or too big.
3. It's ugly in general, It feels really generic, it's just a handful of rooms clustered together around a four way intersection.

**Comment by OneOneThreeEight** [comment]
I think it's a bit too excessively compact. I'm wondering where the Rangers are supposed to be shacked up since they should have their own outpost in their base.

**Comment by Cythisiax** [comment]
Please reverse this PR merge.

**Comment by githubuser4141** [comment]
> Terrible, please do not merge and please un-test merge.
> 
> 1. It has several mistakes such as the defib being too far from the operating table in the tiny shitty medical room.
> 2. It's poorly planned, every room is too small or too big.
> 3. It's ugly in general, It feels really generic, it's just a handful of rooms clustered together around a four way intersection.

I like it, the current base feels pointlessly huge and there's a lot of empty space that isn't used for anything. This feels a lot more 'natural' as it's not a series of reinforced wall rooms in a huge open field. And that first line of issues shouldn't be too hard to fix.

**Comment by Sinbest** [comment]
Ok so apparently this 'new base' is just lifted from another server.

**Comment by AllCorruptingWyrm** [comment]
I'm not sure how I feel about this iteration of the new base here, it feels severely compact and will just create kill zones. Maybe, if there were a surplus of explosives, sure. It just feels like a kill funnel.

**Comment by Tokorizo** [comment]
Not a fan of the design, it is WAY too linear.

**Comment by OneOneThreeEight** [comment]
Closed, if you have any other mapping concepts you'd like to draft, we'd love to have you do some stuff for more compact things to explore in the underground!

**Pull request closed without merging**
