### PR TITLE
General Weapons Adjustments

### PR DESCRIPTION
**Pull request by CatteNoire**
## About The Pull Request
I couldn't come up with an added alliteratively appealing title. I am sad.

## Why It's Good For The Game
Scout rifle: 
Increases the spread on the scout carbine and reduces its slowdown to match SMGs as it's supposed to scout. I also removed the fire_delay preventing it from inheriting the service rifle's fire rate buff.

Repeaters:
Currently, there's no good reason on why you should take a repeater over automatics or double revolvers. This gives repeaters a niche where they have slowdown inbetween SMGs and other rifles. The bullet speed increase also lets them perform better at using their weapons optics. Cowboy repeater gets the fastest bullet speed as it has the weakest damage out of three.

Police rifles:
Police rifles are easily made by shopkeepers and despite this, they somehow perform better than assault carbines. An automatic rifle held together by duct tape and good wishes does more damage and has lower spread than a pre-war rifle. This has been changed.

American 180:
The American 180 is currently a superior minigun. A fraction of the slowdown, easier to reload, easier to obtain, can carry up to 7 magazines of 180 bullets each, more damage, and faster fire rate. Fuck that noise. Nerfs damage and fire rate but it'll still fire faster than its closest SMG peer by .25.

Minigun:
Minigun is shit. Ideally, this makes it not shit. Fire rate buff. Ideally, the result will be that it does a lot of chip damage and stop people from advancing. It might need some tweaking but we'll go from here.

R91:
The R91 has a lot of competitors and it underperforms compared to its peers. Buffing its fire rate and making the slowdown consistent with service rifle and R82 should give it a tangible niche of being able to clear rooms comparable to SMGs or suppress on open fields.

RCW:
RCW currently fires 25 damage beams at an autofire delay of 2. It's also hitscan. The wasteland barely has laser protection. A squad of Knights with RCWs can roll up on anyone and delete them from existence. Damage is reduced.

Gatling laser:
Gatling laser is also bad because it fires slow as heck. Should be good enough for now but I'll change it to match RCW's autofire delay of 2 if it's too fast.

DKS:
I love you, DKS, and it pains me to do this but you're too strong. DKS does more damage than a rangemaster, has AP comparable to an AMR, and great bullet speed. Its damage and AP are toned down but it keeps bullet speed since it's a sniper. It snipes.

Lee-Enfield:
Explorers got scuffed when people swapped them to Lee. The extra damage and faster fire rate should give them a comparable performance to DKS.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by Eluxor** [comment]
Why did you remove the spread? Why do you walk around while carrying it? Its a carbine, not a SMG. Stop trying to buff NCR guns all the time.

**Comment by CatteNoire** [comment]
Did you even read the rest of the code or did your brain jump to NCR buff and disregard the fact that I increased the spread from 1.1 to 1.2? Service rifle has a spread of 1. The scout carbine is currently a worse service rifle with a scope. Giving it a slowdown reduction gives it a niche role and frankly, if a Legionnaire with a SMG loses to a scout rifle, it's a skill issue.

**Comment by cornercube** [comment]
a lot of these changes are already being implemented

**Comment by ScheveningenZonn** [comment]
I'm not going to wait 10 million years for someone else to be finished.

**Pull request merged**
