### PR TITLE
Touches up the NCR Loadouts a bit

### PR DESCRIPTION
**Pull request by BadAtThisGame302**
## About The Pull Request

Removes the M1/N Carbines and replaces them with 9/10mm SMGs. Along with rations, two HT loadouts, Trooper/Corporal loadout tweaks and Captain armor addition.
## Why It's Good For The Game

Fixes up the NCR and removes the M1/N Carbines and replaces them with something NCR Actually use 9/10mm SMGs. Along with the ration add now that the stimpack tweal happened. Captain Armor that was never used was now given a chance to. HT is one slot so why not give them a variety of weaponry to choose from. 

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added rations to every NCR role due to the stimpack hunger nerf
add: Added two more HT loadouts, Flamethrower and Riot Shotgun
tweak: Removed all the M1/N Carbines from the NCR (Except Sergeant) and replaced them with 9/10mm SMGs 
tweak: Removed the LO's main gun and gave him the same pistol as the MO and a telebaton
tweak: Fixed the captain coat not being a child of the captain armor
tweak: Updates the descriptions of the loadouts
:cl:

### CODE REVIEW

**Comment by Jawnner** [comment]
Not everyone needs a burst gun. 

While the M1/R82 aren't canon, they aren't exactly lore-breaking in any way and served as a decent gap in weapons. The entire NCR getting burst weapons isn't the way to go. Also Corporals getting a 14mm pistol is laughable considering the only other loadout that gets a high-caliber gun is/was the Frontline Cent and the NCR Captain.

**Comment by SeniorScore** [comment]
14mm pistol for corporals is comedy

**Comment by Jawnner** [comment]
The HT is one slot because of the weapons they get that enable them to completely pin down enemies. Flamer is eh. Flamer overlaps the Combat Engie, zero reason to pick it other than minelaying which you can't even take real advantage of without being in active combat.

Sledge I'm indifferent on.

**Comment by DaemonTinadel** [comment]
HT shouldnt get a sledge its able to 1 hit you with the daze. Neither should Veteran Decanus imo. Balancing around FNV loadouts isnt really a good state of balance in any case.

The corporal should also not be recieving a 14mm at its current setting. It is .a 44 damage semi auto pistol with .1 extra pen and can probably 3-4 hit people.

I'm fine with all of the smgs tbf every role shouldnt have it. Get rid of the tele baton from logi officer makes no sense to me. Even MPs shouldnt get it.

**Comment by BadAtThisGame302** [comment]
I will replace the super sledge loadout with a riot shotgun and remove the 14mm pistol from corporal when I return home

**Comment by Jawnner** [comment]
Still don't think the NCR should have burst guns en-masse, M1 is good for variance, and HT doesn't need to have even more stuff to do literally everything.

PR should just be closed, imo.

**Comment by BadAtThisGame302** [comment]
Well I hate the M1/N but I guess we need it to "balance the NCR", I'll get you soon... M1..

**Pull request closed without merging**
