### PR TITLE
SM Update

### PR DESCRIPTION
**Pull request by TinkleTingler**
Added
TRAIT_MUTATION_STASIS So unstable Mutagen doesn't affect them
TRAIT_TOXINLOVER Stops healing from normal means, Stimpacks will hurt.
TRAIT_LONGPORKLOVER Doesn't feel upset for eating human
TRAIT_HARD_YARDS Doesn't get slowed down by tiles
TRAIT_GIANT Is a Giant
TRAIT_STUNIMMUNE Can't just beat them with batons
TRAIT_RESISTHEAT Self explanatory TRAIT_PUSHIMMUNE Can't just be pushed out of the way they're Super mutants
TRAIT_TASED_RESISTANCE Can't just tase them

Got rid of speedmod as it wasn't working the right way.

Would like instead of Toxin lover to just disable Metabolism in general or greatly slow it down.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by Weaselburg** [comment]
if this is for playable super mutants, what exactly is the point of giving them so many traits right off the bat? epecially stun/taze immune. this seems extremely excessive and somewhat OP

**Comment by TinkleTingler** [comment]
> if this is for playable super mutants, what exactly is the point of giving them so many traits right off the bat? especially stun/taze immune. this seems extremely excessive and somewhat OP

Their negative traits balance it out, especially as they can't heal normally with Toxin Lover, they also have Poor Aim which makes them wildly inaccurate, These other Traits should've been added in the first published. And it's taze resistant. Considering Super Mutants aren't accessible to everyone and only handed out on special occurrences I think it's fair. Although I do want to make it so they just aren't affected by stims/toxins instead of the reverse way I'm doing now. I like to think the only options while dealing with a Supermutant is to use lethal force, non lethal isn't an option.

**Comment by AllCorruptingWyrm** [comment]
how slow are they?
what about nightkin?

My love, thank though.

**Comment by TinkleTingler** [comment]
> 

They were moving 25% fasting than everyone else but I changed it in be the same speed because of these traits.
Nightkin can be easily added if we get the sprites for em but I don't really like to sprite.

**Comment by ScheveningenZonn** [comment]
Is this test mergable?

**Comment by TinkleTingler** [comment]
> Is this test mergable?

Yeah it is

**Pull request merged**
