### PR TITLE
fix bulk stim crafting because byond dumb (for real this time I promise)

### PR DESCRIPTION
**Pull request by biotear**
Fixed bulk crafting of stimpaks so it makes real ones and not imitation (never forget the stim fluid we lost, brothers). Now I actually put the edit up because my IQ has left the single digits once more.

## About The Pull Request

literally just changed one line of code to stop byond from messing up the bulk craft.

## Why It's Good For The Game

Followers and NCR medics don't need any more sanity debuffs, they have plenty as it is.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

### CODE REVIEW

**Comment by AdamElTablawy** [comment]
files changed: zero?

**Comment by OneOneThreeEight** [comment]
I'm seeing no changes.

**Comment by buffyuwu** [comment]
image
👏

**Comment by biotear** [comment]
> 

ah shit I must have forgot to add it. hang on.

**Pull request merged**
