### PR TITLE
Fixes the chinese uniforms, makes them use the right sprites, and generally cleans up the code for them.

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

I created the chinese uniforms when I first got started in deving and I'm really not happy with them in general, I fixed most of the issues other than the sprites which are still sort of ugly, 

## Why It's Good For The Game

The uniforms are slightly less crap now so people will actually use them.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
**tweak: uniforms use the right sprites now**
**tweak: fixed missing item sprites for the uniforms**
**removed: generals uniforms because ugly and useless**
**removed: sidecap because not lore or history friendly**
/:cl:

### CODE REVIEW

**Comment by Sinbest** [comment]
What does " This code did not runtime during testing" mean?

**Comment by faaaay** [comment]
> What does " This code did not runtime during testing" mean?

It means "your code did not display any runtime errors in Dream Daemon".

**Comment by Sinbest** [comment]
goddammit misclick

**Comment by buffyuwu** [comment]
LGTM

**Pull request merged**
