### PR TITLE
Timelocks have gone a bit too far guys

### PR DESCRIPTION
**Pull request by companoo**
## About The Pull Request

Changes brotherhood and NCR timelocks, bringing a few of them down, namely Head paladin from 80 hours to 40, and slightly bumps up veteran ranger.

## Why It's Good For The Game

Allows more people to play roles sooner, 80 hours of brotherhood play before head paladin is legitimiantly insane, 40 hours is still too much but i didn't wanna be too outlandish. People don't have time to play 80 hours, it makes new people not quit immediatly when they join the first time after seeing the timelocks.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Added new things
add: Added more things
del: Removed old things
tweak: tweaked a few things
balance: rebalanced something
fix: fixed a few things
soundadd: added a new sound thingy
sounddel: removed an old sound thingy
imageadd: added some icons and images
imagedel: deleted some icons and images
spellcheck: fixed a few typos
code: changed some code
refactor: refactored some code
config: changed some config setting
admin: messed with admin stuff
server: something server ops should know
/:cl:

### CODE REVIEW

**Comment by OneOneThreeEight** [comment]
Here's the thing.

If rounds last for three hours (they may last much longer), and you stay alive in-role for that full duration, you just do that 15 times over the course of a few weeks and you're suddenly a lot more equipped to play a higher responsibility role than someone jumping into the hot seat immediately if we didn't have timelocks.

Faction leaders should either require exemptions for long-time players via discord ticket, or a lot of time in-faction to be able to command the entire faction. I don't oppose 80 hrs of a metric right now before we get whitelisting out of the way.

**Comment by companoo** [comment]
Im not opposed to timelocks i just think the time should be shortened, i even added a bit more onto the veteran ranger timelock because we get some spuds playing that role, but 80 hours is pretty crazy.

**Comment by Cythisiax** [comment]
Veteran Ranger timelocks are 50 hours

**Comment by companoo** [comment]
you all suck

**Pull request closed without merging**
