### PR TITLE
Thigh highs are back in style.

### PR DESCRIPTION
**Pull request by OliOliOnsiPree**
## About The Pull Request

This PR gives back striped, red candy cane, green candy cane, rainbow thigh highs and even programmer stockings for the chemistry people in brotherhood of steel. These are mostly for flavor and who doesn't like strips :) 

## Why It's Good For The Game

This is pretty good for the game as it gives more variety if you do chose to put these on instead of having no variety, which doesnt make a little sense, but socks.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
raadds: striped, red candy cane, green candy cane, rainbow thigh highs and even programmer stockings back into the menu
/:cl:

### CODE REVIEW

**Comment by zulixe** [comment]
good PR

**Comment by Al-1ce** [comment]
Followers doctors should get programmer socks, too. It's only natural.

**Comment by OliOliOnsiPree** [comment]
> Followers doctors should get programmer socks, too. It's only natural.

its for everyone anyways it was jut a reference ;)

**Comment by Looreydev** [comment]
Any reason why all of the other stockings etc. are remaining in the file commented out?
@OliOliOnsiPree

**Comment by OliOliOnsiPree** [comment]
> Any reason why all of the other stockings etc. are remaining in the file commented out?
> 
> @OliOliOnsiPree 

Not too sure but if you'll like can readd the rest, as the others ones aren't as good as the ones I recommented in.

**Comment by SeeminglyTypicalUsername** [comment]
bruh

**Pull request merged**
