### PR TITLE
Blacksmithing redone

### PR DESCRIPTION
**Pull request by Pebblesthe2nd**
## About The Pull Request

Always found the port of cit smithing feeling very lacking, no Fallout adaptation at all. This PR does that adaptation.

*New art : Anvils (basic, sandstone, table), ingots (edits + hot state), Furnace (sandstone), all smithed items icons + inhands.

*Sledgehammers can now be used to smith with, base quality. Sparks fly when smithing.

*The possible items you can make reduced in number and improved in quality, adapted to FO. That means new art, inhand sprites, etc. Some recipes will produce a different result, tools unchanged, below the new lineup.
RECIPE_SMALLKNIFE "sdd" //shrink draw draw
RECIPE_SIMPLEMACHETE "dff" //draw fold fold
RECIPE_MACHETE "ddsf" //draw draw shrink fold
RECIPE_WAKI "dfsf" //draw  fold shrink fold
RECIPE_SWORD "dfuf" //draw fold upset fold

RECIPE_KATANA "fffff" //fold fold fold fold fold
RECIPE_HEAVYAXE "udfsf" //upset draw fold shrink fold
RECIPE_HEAVYSABRE "dfb" //draw fold bend

RECIPE_MACE "spsp" //shrink punch shrink punch
RECIPE_SPEAR "ddbf" //draw draw bend fold

* Since I had to  repath sledgehammers a little which requires map stuff I added some of the other new stuff, replacing some of the trashbins with the new one, adding the advice books for blacksmithing and farming to a couple places, the new garden tool rack, the new prefilled seedbin.

## Why It's Good For The Game

BLACKSMIITH
The left ones not material shaded so just the alpha basically, right is the iron ones.
Fewer items but actually decent quality instead of crap is good.
At some point forging weapon damages needs a look at re: the new armors but this is more a style PR.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog
:cl:
tweak: blacksmith recipes
imageadd: Blacksmith rework (anvils, furnace, smithed objects)
code: adjusted fakespark slightly for smithing (unused IPC emote thing)
refactor: sledgehammers subtyped to enable smithing
/:cl:

### CODE REVIEW

**Comment by PraxisApricotte** [comment]
I love all those proposed changes, however I would like to inform, as well as request looking into the unfortunate downgrade the citforge weapons have within the server. It has been brought to my attention that the weapons from this code are actually not usable in combat because of the armors within the F13 meta - while they can be extremely deadly in the cit code where no one is using armors, in F13 where everyone has some kind of armor on them they are effectively useless. While I never actually tested this, it is a concern that should be adressed, if your forge rework has intentions to be used within the game (also with recent armor changed, I am unsure how relevant this is as well, all and all it is important to test the damage of these weapons)

Additionally, I'd like to request that all weapons made through forgery should have the ability to be renamed, like Katanas were in the original CitForging. Take care!

**Comment by SeniorScore** [comment]
> I love all those proposed changes, however I would like to inform, as well as request looking into the unfortunate downgrade the citforge weapons have within the server. It has been brought to my attention that the weapons from this code are actually not usable in combat because of the armors within the F13 meta - while they can be extremely deadly in the cit code where no one is using armors, in F13 where everyone has some kind of armor on them they are effectively useless. While I never actually tested this, it is a concern that should be adressed, if your forge rework has intentions to be used within the game (also with recent armor changed, I am unsure how relevant this is as well, all and all it is important to test the damage of these weapons)
> 
> Additionally, I'd like to request that all weapons made through forgery should have the ability to be renamed, like Katanas were in the original CitForging. Take care!

Armor has been heavily reduced from previous levels when linearmor was still a thing, effective HP on average is lowered compared to what they were previously, and forged weapons were still somewhat usable before that even. It'd be fine in my opinion.

**Comment by SeniorScore** [comment]
Not a fan of all the recipe removals though frankly.

**Comment by TripleShades** [comment]
Personally against the removal of variety of weapons you can smith. It's fine if you didn't want to sprite them all, but they're still servicable; add them back in.

**Comment by PraxisApricotte** [comment]
> Armor has been heavily reduced from previous levels when linearmor was still a thing, effective HP on average is lowered compared to what they were previously, and forged weapons were still somewhat usable before that even. It'd be fine in my opinion.
Yeah, the change in the armor system makes me feel a bit more optimistic about it, but nontheless I believe some testing before fully merging is in order.

**Comment by SeniorScore** [comment]
> > Armor has been heavily reduced from previous levels when linearmor was still a thing, effective HP on average is lowered compared to what they were previously, and forged weapons were still somewhat usable before that even. It'd be fine in my opinion.
> 
> Yeah, the change in the armor system makes me feel a bit more optimistic about it, but nontheless I believe some testing before fully merging is in order.

Gonna say they're perfectly fine and maybe downright too strong with how easy it is for the heavy axe to smack people into crit.

**Comment by OneOneThreeEight** [comment]
Gonna need to ask for balance changes. Higher attack delay for the heavy hitters, give some AP to the smaller weapons so they can punch up their weight class.

**Comment by TripleShades** [comment]
Anyways, asking again, please put the other weapons back in.

**Pull request closed without merging**
