### PR TITLE
Adds ladders (need TM)

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

adds ladders to the game, stairs you can place to climb walls basically.
cannot climb if there is a wall turf either above the ladder, or on the tile you are climbing to. so double high walls cannot be climbed.
will have a lengthy setup time, quite a bit of noise made and maybe a warning in chat if close enough to the ladder being deployed.
beHg4WKJPN

**SETUP TIME SHOWN HERE IS NOT ACCURATE TO HOW IT WILL BE, from WIP version**

## Why It's Good For The Game

more multi-z interactivity.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: ladders!
tweak: made it so stairs can't be climbed if there's a wall blocking the turf above them, OR the one next to it that you get moved onto. 
/:cl:

### CODE REVIEW

**Comment by Jaaackx** [comment]
fuck you checks

**Comment by Al-1ce** [comment]
I understand why the ladder might be destroyed for balance reasons, but what about mechanically? Is it plausable to drop some wood or something once you've climbed? It's trivial but I think it would go well with what you mentioned about the ladder collapsing/breaking.

**Comment by Jaaackx** [comment]
the ladder will become wood when broken yeah, I just didn't add that yet

**Comment by Jaaackx** [comment]
@OneOneThreeEight assuming checks pass, this is ready for a test merge. I still need to do more work before a FULL MERGE, but I could do with the core concept being tested in game.
object sprite is still a placeholder and no sounds are added yet.

**Comment by Jaaackx** [comment]
updated video of use, collapsed sprite is a placeholder.

VrLOfXbFl8

**Comment by Al-1ce** [comment]
> updated video of use, collapsed sprite is a placeholder.
> 
> VrLOfXbFl8

The only real issue I can see with this is that the roofs of most places are completely empty. Dropping from another z-level to attack somebody feels sort-of meta-gamey is all.

**Comment by Jaaackx** [comment]
Sidenote, listing issues with ladders so I can fix later.
- [ ] Ladders not blocked by structures so can climb through windows.

**Comment by Jaaackx** [comment]
assuming checks pass on most recent commit, this is finished from my end. could do with another day/two with updated TM but aside from that it's done.
EWUD0CLs7n
.

**Comment by Jaaackx** [comment]
i lied NOW it's done

**Comment by OneOneThreeEight** [comment]
Are the prior issues addressed?

**Pull request closed without merging**
