### PR TITLE
Added new NCR base

### PR DESCRIPTION
**Pull request by KillerGryphon**
## About The Pull Request

Have you noticed how all NCR bases seem to be facing southward? How about how they have two big areas, both above and underground? In my opinion, there was a lot of bloat that we don't need, and so, with input from NCR and non-NCR players both, I've worked on this new base for the NCR! In addition, there was a large area being underutilized, and I have always felt that there should be more there, so I have added two housing areas, filled with appropriately dangerous stuff, and two mini caves full of nasties.

NCR Base

NCR Base road

NCR base underground

Vet Ranger office

## Why It's Good For The Game

After being supplied concrete from Quarry Junction, Camp Miller has been revamped to be the best frontier outpost in the Yuma desert! All important facilities have been altered to fit the new budget and everything given a new coat of paint. The new roads south and east will open up new gameplay possibilities, be it new patrol routes to take, or flanks an enemy can utilize, shaking up the gameplay in minor ways like this is always good in my opinion.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: A whole new redesigned NCR base on the surface, and new ranger bunks underground.
add: The road south and east of the base is revamped as well.
del: Removed old NCR base on surface and underground.
tweak: tweaked mineral deposits for both NCR and Legion to make them semi-equal. 
/:cl:

### CODE REVIEW

**Comment by githubuser4141** [comment]
Would it be possible to replace the entrance shutters and concrete walls with blast doors or reinforced walls? The "old" base has reinforced walls around all the critical areas (medical, armory, prison blocks) which require lengthy deconstruct or explosives to breach whereas you can delete concrete walls with a welder and it doesn't even drop a girder. Same for shutters which can be destroyed easily with knives or roundstart guns.

**Comment by KillerGryphon** [comment]
Hey there! Sure thing for the shutters, but when you say concrete walls, do you mean ALL the walls? I can definitely do that, I didn't realize concrete was so weak! I just want to make sure that's what you meant.

**Comment by cornercube** [comment]
> Hey there! Sure thing for the shutters, but when you say concrete walls, do you mean ALL the walls? I can definitely do that, I didn't realize concrete was so weak! I just want to make sure that's what you meant.
you might want to replace all concrete walls with supermart walls, since those are the ones with a girder on them

**Comment by githubuser4141** [comment]
> Hey there! Sure thing for the shutters, but when you say concrete walls, do you mean ALL the walls? I can definitely do that, I didn't realize concrete was so weak! I just want to make sure that's what you meant.
> 
> Edit: Note, in my last update, I did make the southern area, which has all the possible concrete entrances, blocked off! Forgot to include that in the title of it.

All the concrete walls are pretty weak I think, even supermarket walls don't leave a girder though I _think_ they take slightly longer to weld? It still takes a while to actually weld so it's not that big of a deal. I'm not a maintainer so if you think all the walls should be toughened that's your choice!

**Comment by BadAtThisGame302** [comment]
Two things, firstly what happened to the gate at the front and secondly the front reinforced walls I feel like should be fences, cause it feels way too secure

**Comment by OneOneThreeEight** [comment]
Ultimately chosen in favor of this mapping. It really changes things up, and it blends being compact with having an actual identity.

**Review by OneOneThreeEight — APPROVED** [review]

**Pull request merged**
