### PR TITLE
Followers Exodus from Oasis/Town Doctors Emerge

### PR DESCRIPTION
**Pull request by Jawnner**
## About The Pull Request

**Followers**

Oasis decided that the Followers could cause too much damage to town relationships due to their own agenda (Mainly Legion aggression) so they kicked them out. However, thanks to contacts in the Brotherhood of Steel and New California Republic, they have been able to safely move to the clinic north of the old Vault-Tec Museum. While losing a couple of volunteers and some doctors who decided to stay in the town and be apart of the clinic, they have bolstered their security force and equipment.

+2 Followers Guard slots, along with three different loadouts. Worn-out old assault carbines from their NCR buddies, police shotguns from some key friends in Oasis, and even AEP7 pistols from the good old Brotherhood of Steel. Due to the exodus, the Followers have even begun to pay more for experienced wastelanders and even former outlaws/raiders to bolster security. These guys are even pros at disassembling pre-war salvage (Technophreak).

-1  Volunteers/Doctors. They decided to stay within Oasis walls. Sad.

Administrator untouched.

Reborn Clinic: Thanks to some of the new guards, and administrators using teachings of former personnel (NCR), they were able to quickly set-up fortifications outside the clinic. (First test of pre-built fortifications which should become the standard tbh.)

StrongDMM_qY4o7k3Ekq

StrongDMM_B0cttem3n8

**Oasis**

+2 Doctors. These guys are pretty good doctors for wastelanders. Some are former Followers, some are former combat medics from wherever they came from. However, the town of Oasis isn't the most advanced. Some say due to how stingy the shopkeeper, the doctor's office isn't as advanced. However, citizens came together and were able to procure some chemistry machines (I might add in a heater, but I wanted to have tiers of medical capabilities in the wasteland). However, the shopkeeper wasn't all too bad, having a contact in the NCR, they were able to get some of those advanced sutures and meshes that the Rangers use in the field. 

StrongDMM_nLIPWOut0i

## Why It's Good For The Game

Followers and Oasis finally seperated, Followers can be a decent military force (I might add in another guard slot tbh, want to get feedback.) Decent-tech town doctor is cool, going for a Doc Mitchell NV type vibe. 

Followers Guard won't get absolutely bullied early and can hold their own and then some.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Oasis Doctor's Office
add: Followers Clinic north of Vault-Tec Museum
del: Followers bunker (cave-in)
tweak: Followers Guard loadouts
/:cl:

### CODE REVIEW

**Comment by cornercube** [comment]
i recommend holding off on this, because someone already in the process of fixing the town, clinic included, and this is going to cause major headaches in the process

**Comment by cornercube** [comment]
also
keep the big armor vest, its very defensively minded equipment with high slowdown which is why the guards were given it, to encourage defense
they need their counter shutters for keeping out people, which is going to be more important due to how easy it will be to corner the followers
they also lack their vending machine for buying things which is the only source of their implants

honestly, just hold off on this update

**Comment by zulixe** [comment]
good change, about time someone did it. followers should not have a monopoly on medical care

**Comment by AllCorruptingWyrm** [comment]
We wouldn't have this monopoly if the Den had not been removed.

**Comment by zulixe** [comment]
> We wouldn't have this monopoly if the Den had not been removed.

what does that have to do with this PR

**Comment by KingMaskito** [comment]
This is my first comment on github, my first time ever making an account, one I made solely for the purpose of weighing in on this issue.

I'll be blunt: This isn't a good change.

One of two things will happen from divorcing the Followers from Oasis in this manner. Either everyone will continue to go to the Followers because why the hell would you go to someone who charges you when you can get it for free
Or
no one will go to the Followers because they're out of the way and then people will complain the Followers as a faction are useless and try to get them removed. Under no circumstance will people reliably go to the Oasis Doc unless they TOO do it for free. And like being a Jannie, Oasis will do it for free because there is nothing more boring than a role with nothing to do and there is literally no mechanical reason to enforce charging. 

Boo AllCorruptingWyrm all you want but that doesn't change the fact that he's right and that his comment is relevant. This same exact thing happened when the Den Doc was a thing. The idea was that Followers get the wastelanders and the den doc gets the unsavories. The idea was that Followers wouldn't have a monopoly on medical care. And yet... and yet they still did. Almost NO ONE besides Den Members went to the Den Doc reliably and the role was more akin to mad scientist than a sewer sawbones due to the lack of patients. Now you're trying to sell us on something that's "The Same but Different This Time (TM)" when we've already seen that this doesn't work.

My point here isn't that separating medical care can't work because I do honestly want more doctors in the wasteland. My point is that this PR is divorced from what actually needs to happen for this kind of change to work. As it stands for the Followers as a faction, they have almost no gameplay loop besides healing. Their supply of patients is already tenuous at best. Further strangling their flow of patients will inevitably kill what little their is to do. Either we need to keep the flow of patients going or, if they get moved out of Oasis, we need to give the Followers something else to do mechanically. This applies to the Oasis doc too.

**Comment by OneOneThreeEight** [comment]
mapmerge pls

**Comment by Snoozer000** [comment]
So followers and town doctor both dont have botany anymore?

**Pull request closed without merging**
