### PR TITLE
new year, new mayoral loadouts

### PR DESCRIPTION
**Pull request by cornercube**
## About The Pull Request
one is dictator themed with a pre-war general theme (getting thrown off the dam optional)
one is wild west themed, the one you are all familiar with
one is vault themed, with the 113 jumpsuit (if only we didnt gamble the GECK for whiskey)
and the last one is business man themed (who run junktown? gizmo does)

in addition to loadouts, the mayor gets a personal defense weapon, the WT-550
an experimental pre-war carbine, its damage is not the highest but it can penetrate a good amount of armor to compensate and has a very wide choice of ammo to choose from, from incendiary to rubber shot

and the sheriffs "sig but better" will be replaced with a unique longarm, the hot-wired AER9
it fires slower than the regular AER9, but can switch to firing overcharged beams
this consumes 5x the energy of a regular shot, but has vastly improved damage and penetration

## Why It's Good For The Game
mayors can run more gimmicks and have slightly more offensive capability, though little defensive capability

unique sig was boring, adds a unique AER9 with alt-fire

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: semi-automatic carbine, the WT-550, for mayor loadout
add: unique AER9 for sheriff
add: renamed general uniform for mayor loadout
add: mayoral loadouts, 4 of them
tweak: sheriff has a normal sig now

/:cl:

### CODE REVIEW

**Comment by OneOneThreeEight** [comment]
sprite previews pls!

**Comment by TripleShades** [comment]
image
Here, fix your linter
please dont use space when in the tab section of code, only use tab for indentations

**Comment by cornercube** [comment]
> sprite previews pls!
still using generic sprites for everything right now
but new ones will be implemented once available

here are the ones currently being use
ncr
d

**Comment by TripleShades** [comment]
image

**Pull request merged**
