### PR TITLE
Pre-built Fortifications (NCR/Legion)

### PR DESCRIPTION
**Pull request by Jawnner**
## About The Pull Request

Added some pre-built fortifications for both camps so maybe less time could be spent on defenses (has been requested in the past.) Also adds some walkways for Legion for their watchtowers, since I like the idea of Legion building more tall with their base with a lot of vantage points. Gave rangers some extra headsets in their outpost to give to potential rangers or replace their own. Beefed up Camp Miller's gatehouse too.

StrongDMM_ZrDpfLAZh2
StrongDMM_3kCvO2QCN2
StrongDMM_THU8UGjPqO

## Why It's Good For The Game

Pre-built fortifications has been requested before, and I think it's a decent idea.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: Pre-built defenses
add: NCR ranger headsets to Ranger Station Oscar
add: Legion lattice walkways on their upper-levels
/:cl:

### CODE REVIEW

**Comment by Looreydev** [comment]
This will inevitably conflict with #384 depending on what gets in first, just for the record. Than can be easily resolved.

**Comment by Jawnner** [comment]
Finally made the Oasis workshop have restrictions. Now they won't get robbed by every swinging dick in the wasteland.

**Comment by VEN0M5** [comment]
> Finally made the Oasis workshop have restrictions. Now they won't get robbed by every swinging dick in the wasteland.

The last time Oasis workshop has access restriction, the door is always broken

**Comment by Jawnner** [comment]
> > Finally made the Oasis workshop have restrictions. Now they won't get robbed by every swinging dick in the wasteland.
> 
> The last time Oasis workshop has access restriction, the door is always broken

Sounds like a failure on Deputies/Sheriffs. The workshop is meant only for Oasis roles, not everyone. A shopkeeper isn't always going to spawn in, and more likely they'll charge their own military force and fellow citizens for needed ammo to defend the town. 

If they don't care that the door is constantly getting broken, then it's w/e.

**Comment by Neveralone1744** [comment]
> > > Finally made the Oasis workshop have restrictions. Now they won't get robbed by every swinging dick in the wasteland.
> > 
> > 
> > The last time Oasis workshop has access restriction, the door is always broken
> 
> Sounds like a failure on Deputies/Sheriffs. The workshop is meant only for Oasis roles, not everyone. A shopkeeper isn't always going to spawn in, and more likely they'll charge their own military force and fellow citizens for needed ammo to defend the town.
> 
> If they don't care that the door is constantly getting broken, then it's w/e. Tbh, it would be better to just move the reloading bench into the armory and leave citizens to their own devices if its a problem.

yeah i gave the work area under a lock in my pr too. its in the vault. good to finally not just share with the wastes

**Comment by Jawnner** [comment]
Oh I forgot to comment. Changed farmhouse doors so they're accessible by Oasis citizens, and I moved the reloading bench to the armory and gave it some GAB1 + 2 and some gunpowder. 

Why: If a shopkeeper doesn't spawn, oasis law enforcement gets kind of fucked because the formerly public reloading bench had a 75% of getting its shit stolen. This became an even bigger problem when I initially put a standard access lock on the workshop with raiders/khans finding small reasons to valid any and all Oasis roles over waahhhhh workshop isn't open to wasters/outlaws/etc.

Workshop was made public again, but lost its reloading bench due to Oasis Government realizing giving outlaws free access to ammo they'll use to rob and kill citizens was kind of dumb.

**Pull request merged**
