### PR TITLE
oasis cargo

### PR DESCRIPTION
**Pull request by lolman360**
pr is going up as a draft so there can be discussion/suggestions about cargopacks and bounties etc here in one place (pr comments)

## About The Pull Request

adds cargo to oasis with some select items + bounties, accessible by shopkeeper

removes cargo from vault as it is disabled and we can only have one cargo shuttle at current

## Why It's Good For The Game

requested feature

cargo has to be carried through a short unsecure section allowing for raids/theft etc

adds bounties which is likely to increase interaction between roles in oasis (farmer/prospector etc to shopkeep)

## Pre-Merge Checklist
- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl: Tzula, lolman360
add: oasis cargo/bounties
del: vault cargo (vault is disabled)
/:cl:

### CODE REVIEW

**Comment by cornercube** [comment]
ncr

just a tiny thing, but can you update the followers basement to have the vending machine again?
and the other bits that might have been moved like the cell charger

**Comment by lolman360** [comment]
accidentally overwrote the follower's basement changes mb

> ncr
> 
> just a tiny thing, but can you update the followers basement to have the vending machine again? and the other bits that might have been moved like the cell charger

**Comment by cornercube** [comment]
> > just a tiny thing, but can you update the followers basement to have the vending machine again? and the other bits that might have been moved like the cell charger

you uhhh, accidentally put the wrong vending machine inside
the followers have one labelled followersterminal and sells different stuff

**Comment by lolman360** [comment]
> you uhhh, accidentally put the wrong vending machine inside the followers have one labelled followersterminal and sells different stuff not the wasteland one

intentional, i hate followers (fixed)

**Pull request closed without merging**
