### PR TITLE
Turns the 'Mayor for Life' loadout for the mayor into the 'Commander in Chief' loadout.

### PR DESCRIPTION
**Pull request by Sinbest**
## About The Pull Request

See above.

The 'Mayor for Life' loadout sucked, so I made it not suck.

I added :

Replaced the semi-ugly outfit they got with some pre-war US Army drip

image

A laser pistol to replace the M1911

A futuristic weapons storage device called a 'holster'

Edit: Removed the outfit example from landmarks.dmi I accidently left in

## Why It's Good For The Game

The oasis general loadout is no longer bad and ugly, which means people will use it.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
add: us army general's overcoat
tweak: modified oasis mayor loadout 
/:cl:

### CODE REVIEW

**Comment by SeeminglyTypicalUsername** [comment]
Can you revert the sprite? This new one isn't that good.

**Comment by AllCorruptingWyrm** [comment]
> 

I think it needs more shading, something to make it more distinct?
That did come off as a bit rude, though, not sure if it was intended or not.

**Comment by Sinbest** [comment]
> Can you revert the sprite? This new one isn't that good.

Revert what sprite?

**Comment by SeeminglyTypicalUsername** [comment]
> > Can you revert the sprite? This new one isn't that good.
> 
> Revert what sprite?

I liked the old one

**Comment by Sinbest** [comment]
> > > Can you revert the sprite? This new one isn't that good.
> > 
> > 
> > Revert what sprite?
> 
> I liked the old one

Well I didn't.

**Comment by Snoozer000** [comment]
> Well I didn't.

I mean, do they really need to compete with each other? If one is a modern oasis general and the newer model is reference to perhaps a restored ancient army uniform is that really a big deal? Why not another loadout?

is there a limit to loadouts? because if people like the oasis general why replace it when you can make a restored army general loadout. Make flavor text about how it was restored. That sounds exactly what some sort of patriotic and power hungry mayor would do. Waste as many manhours, lives and caps to get memorabilia like that just to strut around town and bullying people like that cooky old guy from megaton.

**Comment by Sinbest** [comment]
> I mean, do they really need to compete with each other? If one is a modern oasis general and the newer model is reference to perhaps a restored ancient army uniform is that really a big deal? Why not another loadout?
> 
> is there a limit to loadouts? because if people like the oasis general why replace it when you can make a restored army general loadout. Make flavor text about how it was restored. That sounds exactly what some sort of patriotic and power hungry mayor would do. Waste as many manhours, lives and caps to get memorabilia like that just to strut around town and bullying people like that cooky old guy from megaton.

Completely ignoring the fact that the 'Oasis General' uniform was just a old NCR general's uniform sprite renamed, creating multiple loadouts which are nearly identical purely because a guy wanted a certain item of clothing is not a road I want to send us down.

If he wants it _that much_ he can ask a mapper to add it to the mayor's closet.

**Comment by OneOneThreeEight** [comment]
If you're gonna be an asshole to people on this repo, you're not gonna be able to contribute in the future. First and only warning, @Sinbest.

**Comment by Looreydev** [comment]
> Completely ignoring the fact that the 'Oasis General' uniform was just a old NCR general's uniform sprite renamed, creating multiple loadouts which are nearly identical purely because a guy wanted a certain item of clothing is not a road I want to send us down.

I don't see the issue, like at all. This is a Roleplay Server, how does variety hurt? Sure it is repeating code, but even that can be solved, I really just don't see your point. 

In a perfect world you'd be able to pick together your own loadout, but it isn't perfect.

**Comment by Sinbest** [comment]
> If you're gonna be an asshole to people on this repo, you're not gonna be able to contribute in the future. First and only warning, @Sinbest.

How was I being an asshole? Please explain.

**Comment by Sinbest** [comment]
> > Completely ignoring the fact that the 'Oasis General' uniform was just a old NCR general's uniform sprite renamed, creating multiple loadouts which are nearly identical purely because a guy wanted a certain item of clothing is not a road I want to send us down.
> 
> I don't see the issue, like at all. This is a Roleplay Server, how does variety hurt? Sure it is repeating code, but even that can be solved, I really just don't see your point.
> 
> In a perfect world you'd be able to pick together your own loadout, but it isn't perfect.

Again, I do not want to send us down the road of multiple near identical loadouts because a small group of people wanted different clothing, actual bloat is something we should be avoiding.

**Comment by Sinbest** [comment]
Closing because I was banned

**Pull request closed without merging**
