### PR TITLE
Multi-Z Buildings

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

multi-z to buildings

## Why It's Good For The Game

multi-z

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: add multi-z to buildings
/:cl:

### CODE REVIEW

**Comment by Jaaackx** [comment]
map.
StrongDMM_sRJMkzg3TG

**Comment by TripleShades** [comment]
I know it's funny, but please properly fill out the pr form and changelog.

**Comment by Jaaackx** [comment]
cringe

**Comment by OneOneThreeEight** [comment]
mapmerge pls

**Pull request closed without merging**
