### PR TITLE
removes ability to make synthtissue

### PR DESCRIPTION
**Pull request by Jaaackx**
## About The Pull Request

removes the ability to make synthtissue through chemistry. chemical itself is still available to admin spawn.
another epic deletion PR

## Why It's Good For The Game

used to extend revival timers past the 20 minute mark, effectively making death/organ decay meaningless if you're with the followers.
hard caps revival timer at 20 minutes.

## Pre-Merge Checklist

- [ ] You tested this on a local server.
- [ ] This code did not runtime during testing.
- [ ] You documented all of your changes.

## Changelog

:cl:
del: synthtissue required reagents and catalyst
/:cl:

### CODE REVIEW

**Comment by VEN0M5** [comment]
Can botany rng get it?

**Comment by SeniorScore** [comment]
Meaningless is a bit much, still think its a bad PR, just going to get those restart votes happening even faster.

**Comment by Jaaackx** [comment]
cope

**Comment by SeniorScore** [comment]
I will, grappling and churning over this changes rn

**Comment by BigMawrk** [comment]
revival takes way longer if you're decayed because the followers almost never have synthtissue on hand, it'd make sense if you made the recipe something that needs to be cooked like the fermichem stuff but it feels like removing content is the go-to for a lot of fixes like this, i dont think its a good pr

**Comment by SeniorScore** [comment]
> revival takes way longer if you're decayed because the followers almost never have synthtissue on hand, it'd make sense if you made the recipe something that needs to be cooked like the fermichem stuff but it feels like removing content is the go-to for a lot of fixes like this, i dont think its a good pr

it is cooked currently.
Still a bad PR, think porting the PR trip was talking about that makes less of an immediate 'why yes you're good to go after some slapping shit on your organs' and makes recovering from death a bit more of a process, keeps it, still discourages death a little bit more than it does currently (hardly at all)

**Comment by Jaaackx** [comment]
> revival takes way longer if you're decayed because the followers almost never have synthtissue on hand

The entire point of this PR is that revival past the 20 minute cap for organ decay should **not be possible**. There is absolutely no circumstance in which a Follower should be able to revive an incredibly decayed corpse they fished out of the sewers 2 hours later.

20 minutes should be the cap for revivals, no exceptions.

**Comment by Neveralone1744** [comment]
to be honest though followers are the mains for this ncr can do the same and bos. but people go to followers. with removal there should be a change to support the new way this will affect the game. which this will severely affect the game.

**Comment by Jaaackx** [comment]
>to be honest though followers are the mains for this ncr can do the same and bos. but people go to followers. with removal there should be a change to support the new way this will affect the game. which this will severely affect the game.

Tough. Don't die. You have 20 minutes to be found and revived, synthtissue makes absolutely no sense within the setting and strips all fear of your character being removed from a round. This is not meant to be a hugbox, stop treating it like one.

**Comment by VEN0M5** [comment]
You could just make synthtissue grant a permanent trauma as a nerf

**Comment by Neveralone1744** [comment]
> > to be honest though followers are the mains for this ncr can do the same and bos. but people go to followers. with removal there should be a change to support the new way this will affect the game. which this will severely affect the game.
> 
> Tough. Don't die. You have 20 minutes to be found and revived, synthtissue makes absolutely no sense within the setting and strips all fear of your character being removed from a round. This is not meant to be a hugbox, stop treating it like one.

that works for you as a person but for the server without something to help the shift it will do more harm than good. like i get that people coming back can be somewhat immersion breaking but just saying dead is dead is simply an xcom outlook. now i love xcom but its also pure torture and is niche. you have to give people a chance of revival and yeah sure 20 min is decent for a faction personnel but who is gonna help the waster or other such? this alone just helps the meta buddies.

**Comment by Jaaackx** [comment]
It's ultimately just a decision for admins/Schev and there's not much point doing a back and forth here

Entirely depends on whether or not Schev wants death to have considerably more impact, or whether they prefer to keep characters in the round, neither of which are bad takes, I just prefer the former, it was how Fallout 13 code worked for the majority of the time prior to the Citadel rebase and never negatively impacted round length.

**Comment by AllCorruptingWyrm** [comment]
As someone who mains followers, we don't get any patients since the pop has dyed off. We get them most around the 30-40m mark but nothing further.

On the otherside I'm not sure synthtissue colonies being removed is a good idea because most deaths aren't from incompetency, it's generally from the server lag or being frozen in place for a few seconds with the other circumstance being one time players who thought they could kill a Handy.. Or mobs that stun you i.e venus flytraps.

Ultimately, this is an issue of a new era of FO13 and reverting back to an idealized past just limits us. Why not implement a mechanic that requires resources that the Followers/BoS can engage with that enables revival at a cost?

**Comment by OneOneThreeEight** [comment]
closing in favor of the nerf PR instead

**Pull request closed without merging**
