### PR TITLE
Removes most dense rock from the surface map

### PR DESCRIPTION
**Pull request by XElectricX**
## About The Pull Request

Removed most annoying dense rocks on the surface map. Left dense rocks around faction bases untouched. Khan camp's dense rock was moved to be closer to the actual camp. Not sure if it was meant to be protective so it is left clustered around it with some openings.
image

Standard rocks had their chance of being dense rocks removed. The standard rocks underground were replaced with /turf/closed/mineral/low_chance/underground, which retain that chance. Had to brush over a bunch of /high_chance/ rocks so I added in some clusters manually. Not sure if is too much or too many, tried to match the amount that was deleted.
image

## Why It's Good For The Game

Dense rock in the surface is anti-fun for building and digging. Underground mining is still filled with RNG dense rocks, so it was not affected.

## Pre-Merge Checklist

- [x] You tested this on a local server.
- [x] This code did not runtime during testing.
- [x] You documented all of your changes.

## Changelog

:cl:
tweak: Annoying dense rocks on the surface map removed, underground rocks still work the same; high value rocks more spread out instead of solid concentrations
/:cl:

### CODE REVIEW

**Comment by XElectricX** [comment]
Do not TM, something funky happened to the map while fixing another conflict.

**Comment by XElectricX** [comment]
Ready for TM.

**Comment by OneOneThreeEight** [comment]
Map-merge one more time for me!

**Comment by XElectricX** [comment]
#162 did not document what changes were made to the underground map so I just overwrote it. I'm not spending another 2 hours brushing over things for what looks to be dirt decals added. Will add back in if given a screenshot of the changes.

**Comment by cornercube** [comment]
important thing you need to add is the followers vending machine directly next to the medical vendor in the basement /obj/machinery/mineral/wasteland_vendor/followerterminal

and a cell charger on the chemistry desk


ncr

**Review by OneOneThreeEight — COMMENTED** [review]
yeah do as above pls! good ideas.

**Comment by XElectricX** [comment]
image
Changed positions to make more sense. Cells and cell charger moved to their Mechanics and Storage room. The vendor was moved to the other wall so it could be accessed from both sides, like the Nanomed. The organs freezer was blocking it, which makes it look awkward. Amount wasn't specified so I added 4 pistols.

**Comment by cornercube** [comment]
> image Changed positions to make more sense. Cells and cell charger moved to their Mechanics and Storage room. The vendor was moved to the other wall so it could be accessed from both sides, like the Nanomed. The organs freezer was blocking it, which makes it look awkward. Amount wasn't specified so I added 4 pistols.

fair changes
there were only 2 additional pistols in the lockers

**Pull request merged**
